UPDATE it_trend_directions SET name = 'Python', emoji = '🐍', description = 'Универсальный язык: бэкенд, анализ данных, автоматизация, ИИ.' WHERE direction_key = 'python';
UPDATE it_trend_directions SET name = 'JavaScript / TypeScript', emoji = '🟨', description = 'Язык веба: фронтенд, Node.js, кросс-платформенные приложения.' WHERE direction_key = 'javascript';
UPDATE it_trend_directions SET name = 'Go (Golang)', emoji = '🐹', description = 'Быстрый компилируемый язык для нагруженных сервисов и облака.' WHERE direction_key = 'go';
UPDATE it_trend_directions SET name = 'Rust', emoji = '🦀', description = 'Системный язык с безопасной памятью — растущий тренд.' WHERE direction_key = 'rust';
UPDATE it_trend_directions SET name = 'ИИ и машинное обучение', emoji = '🧠', description = 'Нейросети, LLM, компьютерное зрение, генеративный ИИ.' WHERE direction_key = 'ai-ml';
UPDATE it_trend_directions SET name = 'Data Science и аналитика', emoji = '📊', description = 'Работа с данными, BigData, инженерия данных, ML-пайплайны.' WHERE direction_key = 'data';
UPDATE it_trend_directions SET name = 'DevOps и облака', emoji = '☁️', description = 'CI/CD, Kubernetes, контейнеры, инфраструктура как код.' WHERE direction_key = 'devops';
UPDATE it_trend_directions SET name = 'Веб-разработка', emoji = '🌐', description = 'Современный фронтенд и бэкенд, фреймворки, API.' WHERE direction_key = 'web';
UPDATE it_trend_directions SET name = 'Мобильная разработка', emoji = '📱', description = 'iOS, Android, кросс-платформенные приложения.' WHERE direction_key = 'mobile';
UPDATE it_trend_directions SET name = 'Кибербезопасность', emoji = '🔒', description = 'Защита данных, пентест, безопасная разработка.' WHERE direction_key = 'security';
UPDATE it_trend_directions SET name = 'IoT и автоматизация', emoji = '🤖', description = 'Промышленная автоматизация, датчики, умные устройства.' WHERE direction_key = 'iot';
UPDATE it_trend_directions SET name = 'Low-code / No-code', emoji = '⚡', description = 'Быстрая разработка приложений без глубокого кода.' WHERE direction_key = 'lowcode';
UPDATE it_trend_sources SET name = 'Хабр · Разработка' WHERE code = 'habr-dev';
UPDATE it_trend_sources SET name = 'Хабр · Машинное обучение' WHERE code = 'habr-ml';
UPDATE it_trend_sources SET name = 'Хабр · Python' WHERE code = 'habr-python';
UPDATE it_trend_sources SET name = 'Хабр · Go' WHERE code = 'habr-go';
UPDATE it_trend_sources SET name = 'Хабр · JavaScript' WHERE code = 'habr-js';
UPDATE it_trend_sources SET name = 'Хабр · DevOps' WHERE code = 'habr-devops';
UPDATE it_trend_sources SET name = 'Наш канал MAX' WHERE code = 'our-max';
