import { Profession } from "./types";

/**
 * База профессий с привязкой к шкалам и вузам.
 * 36 профессий покрывают основные направления: IT, медицина, инженерия,
 * творчество, право, экономика, военные, наука, педагогика.
 */
export const PROFESSIONS: Profession[] = [
  // ─── IT / ИНЖЕНЕРИЯ ───────────────────────────────────────────────────
  {
    id: "software-engineer",
    title: "Программист / разработчик ПО",
    emoji: "💻",
    short: "Создаёт сайты, мобильные приложения, серверы. Самая массовая IT-профессия.",
    riasec: ["I", "C"],
    values: ["income", "freedom", "creativity"],
    abilities: ["analytical", "creative"],
    subjects: ["informatics", "math", "english"],
    egeSubjects: ["math_prof", "informatics", "russian"],
    universityIds: ["mfti", "itmo", "hse", "msu", "mifi", "bauman", "spbpu", "miet", "fefu", "susu", "sfu", "ssau", "tusur"],
    salaryFrom: 120,
    salaryTo: 450,
    outlook: "rising",
    dayInLife: "Утром — стендап с командой. Днём — пишет код, ревьюит чужие правки, дебажит. Большая часть работы — мышление, а не печать на клавиатуре.",
  },
  {
    id: "data-scientist",
    title: "Аналитик данных / Data Scientist",
    emoji: "📊",
    short: "Из больших данных делает выводы и обучает модели машинного обучения.",
    riasec: ["I", "C"],
    values: ["science", "income"],
    abilities: ["analytical"],
    subjects: ["math", "informatics", "english"],
    egeSubjects: ["math_prof", "informatics", "russian"],
    universityIds: ["mfti", "hse", "itmo", "mifi", "msu", "fefu", "sfu"],
    salaryFrom: 150,
    salaryTo: 500,
    outlook: "rising",
    dayInLife: "Чистит датасеты, строит дашборды, обучает модели, объясняет результаты бизнесу.",
  },
  {
    id: "cybersecurity",
    title: "Специалист по кибербезопасности",
    emoji: "🛡",
    short: "Защищает информационные системы. Военные, банки, госструктуры.",
    riasec: ["I", "C"],
    values: ["service", "stability", "income"],
    abilities: ["analytical", "memory"],
    subjects: ["math", "informatics", "physics"],
    egeSubjects: ["math_prof", "informatics", "russian"],
    universityIds: ["mifi", "bauman", "itmo", "vka-mozhaisky", "vmedu", "sfedu", "vgtu"],
    salaryFrom: 130,
    salaryTo: 400,
    outlook: "rising",
    dayInLife: "Мониторит инциденты, расследует утечки, проводит пентесты, пишет регламенты.",
  },
  {
    id: "mechanical-engineer",
    title: "Инженер-конструктор",
    emoji: "⚙",
    short: "Проектирует машины, авиатехнику, оборудование.",
    riasec: ["R", "I"],
    values: ["stability", "creativity"],
    abilities: ["spatial", "mechanical", "analytical"],
    subjects: ["math", "physics", "informatics"],
    egeSubjects: ["math_prof", "physics", "russian"],
    universityIds: ["bauman", "mai", "spbpu", "ssau", "pstu", "nntu-alekseev", "miit"],
    salaryFrom: 75,
    salaryTo: 220,
    outlook: "rising",
    dayInLife: "Работает в SolidWorks/КОМПАС, рассчитывает прочность, ходит в цех, согласует чертежи.",
  },
  {
    id: "aerospace",
    title: "Инженер ракетно-космической техники",
    emoji: "🚀",
    short: "Проектирует ракеты, спутники, двигатели.",
    riasec: ["R", "I"],
    values: ["science", "service"],
    abilities: ["analytical", "spatial", "mechanical"],
    subjects: ["math", "physics"],
    egeSubjects: ["math_prof", "physics", "russian"],
    universityIds: ["mai", "bauman", "mfti", "ssau", "pstu"],
    salaryFrom: 80,
    salaryTo: 250,
    outlook: "rising",
    dayInLife: "Считает баллистику, проектирует узлы двигателей, согласует ТЗ с заказчиком (Роскосмос).",
  },
  {
    id: "nuclear-engineer",
    title: "Инженер-атомщик",
    emoji: "☢️",
    short: "Работает на АЭС, в реакторах, ядерной медицине.",
    riasec: ["R", "I"],
    values: ["stability", "income", "science"],
    abilities: ["analytical", "memory", "mechanical"],
    subjects: ["math", "physics", "chemistry"],
    egeSubjects: ["math_prof", "physics", "russian"],
    universityIds: ["mifi", "spbpu", "tpu", "urfu"],
    salaryFrom: 100,
    salaryTo: 300,
    outlook: "stable",
    dayInLife: "Дежурит на пульте, ведёт техкарту, отвечает за безопасность реактора.",
  },

  // ─── МЕДИЦИНА И БИОТЕХ ────────────────────────────────────────────────
  {
    id: "doctor",
    title: "Врач-лечебник",
    emoji: "⚕",
    short: "Лечит пациентов в больнице или поликлинике. 6 лет вуза + ординатура.",
    riasec: ["S", "I"],
    values: ["service", "stability"],
    abilities: ["memory", "social", "analytical"],
    subjects: ["biology", "chemistry"],
    egeSubjects: ["chemistry", "biology", "russian"],
    universityIds: ["sechenov", "vma-kirov", "kazgmu", "usmu", "rsmu-rostov", "pimu", "ssmu", "psma", "kursk-medical", "bgmu", "vlgma", "kubgmu", "msmu-evdokimov", "ngmu", "ulsu"],
    salaryFrom: 70,
    salaryTo: 250,
    outlook: "rising",
    dayInLife: "Обход палат, приём пациентов, оформление истории болезни, консилиумы.",
  },
  {
    id: "surgeon",
    title: "Хирург",
    emoji: "🔪",
    short: "Оперирует. Самая ответственная и высокооплачиваемая мед. специальность.",
    riasec: ["R", "I", "S"],
    values: ["service", "power", "income"],
    abilities: ["analytical", "memory", "mechanical"],
    subjects: ["biology", "chemistry"],
    egeSubjects: ["chemistry", "biology", "russian"],
    universityIds: ["sechenov", "vma-kirov", "kazgmu", "rsmu-rostov", "pimu"],
    salaryFrom: 120,
    salaryTo: 500,
    outlook: "stable",
    dayInLife: "Операции 4–8 часов в день, плановые и экстренные. Дежурства.",
  },
  {
    id: "dentist",
    title: "Стоматолог",
    emoji: "🦷",
    short: "Лечит зубы. Частная практика — высокий доход.",
    riasec: ["R", "S"],
    values: ["income", "stability"],
    abilities: ["mechanical", "spatial", "social"],
    subjects: ["biology", "chemistry"],
    egeSubjects: ["chemistry", "biology", "russian"],
    universityIds: ["msmu-evdokimov", "sechenov", "kazgmu"],
    salaryFrom: 100,
    salaryTo: 400,
    outlook: "stable",
    dayInLife: "Приём 6–10 пациентов в день, лечение/протезирование, общение с пациентами.",
  },
  {
    id: "psychologist",
    title: "Психолог / психотерапевт",
    emoji: "🧠",
    short: "Помогает людям с эмоциями, отношениями, травмами.",
    riasec: ["S", "I"],
    values: ["service", "creativity"],
    abilities: ["social", "verbal", "memory"],
    subjects: ["biology", "social", "literature"],
    egeSubjects: ["biology", "social", "russian"],
    universityIds: ["msu", "spbgu", "hse", "rggu", "rgsu"],
    salaryFrom: 60,
    salaryTo: 250,
    outlook: "rising",
    dayInLife: "5–7 консультаций в день, ведение протоколов, супервизии, чтение исследований.",
  },
  {
    id: "biologist",
    title: "Биолог / генетик",
    emoji: "🧬",
    short: "Изучает живые системы. Биотех — одна из самых растущих отраслей.",
    riasec: ["I"],
    values: ["science"],
    abilities: ["analytical", "memory"],
    subjects: ["biology", "chemistry"],
    egeSubjects: ["biology", "chemistry", "russian"],
    universityIds: ["msu", "spbgu", "nsu", "tsu", "kfu", "isu", "kemsu"],
    salaryFrom: 60,
    salaryTo: 200,
    outlook: "rising",
    dayInLife: "Работа с пробирками и микроскопами, чтение статей, написание грантов.",
  },
  {
    id: "veterinarian",
    title: "Ветеринарный врач",
    emoji: "🐾",
    short: "Лечит животных. Растущий рынок частных клиник.",
    riasec: ["S", "R"],
    values: ["service"],
    abilities: ["mechanical", "social", "memory"],
    subjects: ["biology", "chemistry"],
    egeSubjects: ["biology", "chemistry", "russian"],
    universityIds: ["mgavm"],
    salaryFrom: 50,
    salaryTo: 180,
    outlook: "rising",
    dayInLife: "Приём, операции, диагностика, общение с владельцами.",
  },

  // ─── ХИМИЯ / БИОТЕХ ──────────────────────────────────────────────────
  {
    id: "chemist",
    title: "Химик-технолог",
    emoji: "🧪",
    short: "Разрабатывает материалы: лекарства, полимеры, удобрения.",
    riasec: ["I", "R"],
    values: ["science", "income"],
    abilities: ["analytical", "mechanical"],
    subjects: ["chemistry", "math", "physics"],
    egeSubjects: ["chemistry", "math_prof", "russian"],
    universityIds: ["muct", "msu", "kazgmu", "tpu", "kubsu"],
    salaryFrom: 70,
    salaryTo: 220,
    outlook: "stable",
    dayInLife: "Опыты, анализ образцов, написание отчётов, общение с производством.",
  },

  // ─── ЭКОНОМИКА И ФИНАНСЫ ─────────────────────────────────────────────
  {
    id: "economist",
    title: "Экономист / финансист",
    emoji: "💰",
    short: "Анализ рынков, инвестиций, финансовое планирование.",
    riasec: ["E", "C", "I"],
    values: ["income", "stability", "power"],
    abilities: ["analytical", "verbal"],
    subjects: ["math", "social", "english"],
    egeSubjects: ["math_prof", "social", "russian"],
    universityIds: ["hse", "msu", "spbgu", "fa-gov", "plekhanov", "ranepa", "spbguef", "vavt"],
    salaryFrom: 90,
    salaryTo: 350,
    outlook: "stable",
    dayInLife: "Готовит отчёты, считает модели, выступает на совещаниях, общается с клиентами.",
  },
  {
    id: "banker",
    title: "Банкир / инвестбанкир",
    emoji: "🏦",
    short: "Работа с капиталом крупных компаний и частных клиентов.",
    riasec: ["E", "C"],
    values: ["income", "power"],
    abilities: ["analytical", "leadership", "verbal"],
    subjects: ["math", "social", "english"],
    egeSubjects: ["math_prof", "social", "russian", "foreign"],
    universityIds: ["fa-gov", "hse", "vavt", "mgimo", "spbguef"],
    salaryFrom: 150,
    salaryTo: 800,
    outlook: "stable",
    dayInLife: "Анализ сделок, переговоры, презентации, поздние совещания.",
  },
  {
    id: "accountant",
    title: "Бухгалтер / аудитор",
    emoji: "📋",
    short: "Стабильная профессия с высоким спросом во всех отраслях.",
    riasec: ["C"],
    values: ["stability"],
    abilities: ["analytical", "memory"],
    subjects: ["math", "social"],
    egeSubjects: ["math_prof", "social", "russian"],
    universityIds: ["plekhanov", "fa-gov", "ranepa", "spbguef", "usue", "vlsu"],
    salaryFrom: 50,
    salaryTo: 180,
    outlook: "stable",
    dayInLife: "Отчётность, проводки, общение с налоговой, закрытие периода.",
  },

  // ─── ПРАВО И УПРАВЛЕНИЕ ──────────────────────────────────────────────
  {
    id: "lawyer",
    title: "Юрист / адвокат",
    emoji: "⚖",
    short: "Защищает интересы клиентов в суде и при сделках.",
    riasec: ["E", "C"],
    values: ["income", "power", "service"],
    abilities: ["verbal", "memory", "analytical"],
    subjects: ["social", "history", "russian"],
    egeSubjects: ["social", "history", "russian"],
    universityIds: ["msu", "spbgu", "hse", "ranepa", "vu-mo", "kfu"],
    salaryFrom: 70,
    salaryTo: 400,
    outlook: "stable",
    dayInLife: "Чтение договоров, суды, переговоры, составление документов.",
  },
  {
    id: "diplomat",
    title: "Дипломат / международник",
    emoji: "🌍",
    short: "Представляет интересы страны за рубежом.",
    riasec: ["E", "S"],
    values: ["service", "power"],
    abilities: ["verbal", "memory", "social", "leadership"],
    subjects: ["english", "history", "social"],
    egeSubjects: ["social", "foreign", "history", "russian"],
    universityIds: ["mgimo", "vavt", "spbgu", "vu-mo"],
    salaryFrom: 120,
    salaryTo: 400,
    outlook: "stable",
    dayInLife: "Встречи, переговоры, аналитические записки, командировки.",
  },
  {
    id: "civil-servant",
    title: "Госслужащий",
    emoji: "🏛",
    short: "Работа в министерствах, муниципалитетах, ведомствах.",
    riasec: ["C", "E"],
    values: ["stability", "power", "service"],
    abilities: ["analytical", "verbal", "memory"],
    subjects: ["social", "history", "russian"],
    egeSubjects: ["math_prof", "social", "russian"],
    universityIds: ["ranepa", "ranepa-spb", "siu-ranepa", "msu", "hse"],
    salaryFrom: 60,
    salaryTo: 250,
    outlook: "stable",
    dayInLife: "Документы, совещания, поручения, контроль исполнения.",
  },
  {
    id: "manager",
    title: "Менеджер / руководитель",
    emoji: "📈",
    short: "Управляет командой и процессами в компании.",
    riasec: ["E"],
    values: ["income", "power", "team"],
    abilities: ["leadership", "social", "verbal"],
    subjects: ["social", "english", "math"],
    egeSubjects: ["math_prof", "social", "russian"],
    universityIds: ["hse", "ranepa", "plekhanov", "spbguef", "vavt"],
    salaryFrom: 100,
    salaryTo: 500,
    outlook: "stable",
    dayInLife: "Совещания, постановка задач, отчёты, общение с командой и клиентами.",
  },
  {
    id: "entrepreneur",
    title: "Предприниматель",
    emoji: "🚀",
    short: "Создаёт свой бизнес. Высокий риск и высокий потенциал.",
    riasec: ["E"],
    values: ["income", "freedom", "creativity", "power"],
    abilities: ["leadership", "creative", "social"],
    subjects: ["math", "social", "english"],
    egeSubjects: ["math_prof", "social", "russian"],
    universityIds: ["hse", "spbpu", "ranepa", "plekhanov"],
    salaryFrom: 0,
    salaryTo: 2000,
    outlook: "rising",
    dayInLife: "Всё подряд: продажи, найм, тушение пожаров. Без потолка дохода и без выходных.",
  },

  // ─── ТВОРЧЕСТВО ──────────────────────────────────────────────────────
  {
    id: "designer",
    title: "Дизайнер (UX / графика / интерьер)",
    emoji: "🎨",
    short: "Создаёт визуальные продукты. UX/UI — топ-IT-профессия.",
    riasec: ["A", "I"],
    values: ["creativity", "freedom", "income"],
    abilities: ["creative", "spatial", "verbal"],
    subjects: ["art", "informatics", "literature"],
    egeSubjects: ["literature", "russian"],
    universityIds: ["vstu-msu-design", "rea-kosygin", "stroganov", "spbgasu", "nsuada"],
    salaryFrom: 80,
    salaryTo: 300,
    outlook: "rising",
    dayInLife: "Скетчи, прототипы, согласования с клиентом, работа в Figma/Photoshop.",
  },
  {
    id: "architect",
    title: "Архитектор",
    emoji: "🏛",
    short: "Проектирует здания и города. Сочетание инженерии и творчества.",
    riasec: ["A", "R", "I"],
    values: ["creativity", "stability"],
    abilities: ["spatial", "creative", "analytical"],
    subjects: ["math", "art", "physics"],
    egeSubjects: ["math_prof", "russian"],
    universityIds: ["spbgasu", "mgsu", "nsuada", "pnu"],
    salaryFrom: 70,
    salaryTo: 250,
    outlook: "stable",
    dayInLife: "Чертежи в AutoCAD/Revit, объекты, согласования с заказчиком и стройнадзором.",
  },
  {
    id: "writer",
    title: "Писатель / журналист / сценарист",
    emoji: "✍",
    short: "Работает со словом — печатным, экранным, эфирным.",
    riasec: ["A", "S"],
    values: ["creativity", "freedom"],
    abilities: ["verbal", "creative", "memory"],
    subjects: ["literature", "russian", "history"],
    egeSubjects: ["russian", "literature", "social"],
    universityIds: ["msu", "spbgu", "rggu", "hse", "msulit", "spbguki"],
    salaryFrom: 40,
    salaryTo: 250,
    outlook: "stable",
    dayInLife: "Интервью, ресёрч, написание текстов, монтаж, общение с редактором.",
  },
  {
    id: "actor",
    title: "Актёр / режиссёр",
    emoji: "🎭",
    short: "Театр, кино, телевидение. Конкурс в вуз — самый высокий в стране.",
    riasec: ["A", "S"],
    values: ["creativity", "power"],
    abilities: ["creative", "verbal", "social"],
    subjects: ["literature", "art"],
    egeSubjects: ["literature", "russian"],
    universityIds: ["gitis", "spbguki"],
    salaryFrom: 30,
    salaryTo: 500,
    outlook: "stable",
    dayInLife: "Репетиции, спектакли/съёмки, читки пьес, кастинги.",
  },
  {
    id: "musician",
    title: "Музыкант / композитор",
    emoji: "🎼",
    short: "Исполнительство или композиция. Требуется музыкальная школа в анамнезе.",
    riasec: ["A"],
    values: ["creativity", "freedom"],
    abilities: ["creative", "memory"],
    subjects: ["art", "literature"],
    egeSubjects: ["literature", "russian"],
    universityIds: ["msu-conservatory"],
    salaryFrom: 30,
    salaryTo: 250,
    outlook: "stable",
    dayInLife: "Репетиции 4–6 часов в день, концерты, преподавание.",
  },
  {
    id: "artist",
    title: "Художник / иллюстратор",
    emoji: "🖼",
    short: "Живопись, графика, иллюстрация книг и игр.",
    riasec: ["A"],
    values: ["creativity", "freedom"],
    abilities: ["creative", "spatial"],
    subjects: ["art", "literature"],
    egeSubjects: ["literature", "russian"],
    universityIds: ["mgaip-surikov", "stroganov"],
    salaryFrom: 30,
    salaryTo: 250,
    outlook: "stable",
    dayInLife: "Эскизы, написание полотен, выставки, общение с галереями и заказчиками.",
  },

  // ─── ВОЕННЫЕ ─────────────────────────────────────────────────────────
  {
    id: "military-officer",
    title: "Офицер ВС РФ",
    emoji: "🎖",
    short: "Кадровый военный. Обучение в вузе МО — бесплатно, с полным гособеспечением.",
    riasec: ["R", "E"],
    values: ["service", "stability"],
    abilities: ["leadership", "mechanical", "memory"],
    subjects: ["math", "physics", "pe"],
    egeSubjects: ["math_prof", "physics", "russian"],
    universityIds: ["vva-zhukovsky", "vka-mozhaisky", "vma-kirov", "mvaa", "kvvaul", "rau", "kazvvku", "omsk-tank", "pgma-tof", "marines-cher", "vmedu", "rea-yelets"],
    salaryFrom: 80,
    salaryTo: 300,
    outlook: "stable",
    dayInLife: "Подъём 6:00, утренний осмотр, занятия, тренировки, командование.",
  },
  {
    id: "pilot",
    title: "Лётчик (военный / гражданский)",
    emoji: "✈",
    short: "Управляет самолётом или вертолётом. Требования к здоровью максимальные.",
    riasec: ["R", "I"],
    values: ["service", "income", "freedom"],
    abilities: ["spatial", "mechanical", "analytical"],
    subjects: ["math", "physics", "pe"],
    egeSubjects: ["math_prof", "physics", "russian"],
    universityIds: ["kvvaul", "uvaul", "spbgu-civil-aviation", "vva-zhukovsky"],
    salaryFrom: 150,
    salaryTo: 700,
    outlook: "rising",
    dayInLife: "Предполётная подготовка, полёт 6–10 часов, разбор полётов, тренажёр.",
  },
  {
    id: "police-officer",
    title: "Следователь / прокурор",
    emoji: "👮",
    short: "Расследует преступления или поддерживает государственное обвинение.",
    riasec: ["E", "S"],
    values: ["service", "stability", "power"],
    abilities: ["analytical", "verbal", "memory"],
    subjects: ["social", "history", "russian"],
    egeSubjects: ["social", "history", "russian"],
    universityIds: ["msu", "spbgu", "vu-mo"],
    salaryFrom: 70,
    salaryTo: 200,
    outlook: "stable",
    dayInLife: "Допросы, выезды, написание процессуальных документов, суды.",
  },

  // ─── ОБРАЗОВАНИЕ И НАУКА ─────────────────────────────────────────────
  {
    id: "teacher",
    title: "Учитель / педагог",
    emoji: "📚",
    short: "Учит детей в школе. Дефицитная и нужная профессия.",
    riasec: ["S", "A"],
    values: ["service", "stability"],
    abilities: ["verbal", "social", "memory"],
    subjects: ["russian", "literature", "history"],
    egeSubjects: ["russian", "social", "literature"],
    universityIds: ["mpgu", "msu", "rsu-esenin"],
    salaryFrom: 40,
    salaryTo: 120,
    outlook: "stable",
    dayInLife: "Уроки, проверка тетрадей, родительские собрания, методическая работа.",
  },
  {
    id: "researcher",
    title: "Учёный / научный сотрудник",
    emoji: "🔬",
    short: "Делает науку в РАН, университете или НИИ. Долгий путь, кандидатская/докторская.",
    riasec: ["I"],
    values: ["science", "freedom"],
    abilities: ["analytical", "verbal", "memory"],
    subjects: ["math", "physics", "biology", "chemistry"],
    egeSubjects: ["math_prof", "physics", "russian"],
    universityIds: ["msu", "mfti", "spbgu", "nsu", "tsu", "novsu", "isu", "ssau", "irnitu"],
    salaryFrom: 50,
    salaryTo: 200,
    outlook: "stable",
    dayInLife: "Эксперименты/расчёты, чтение статей, написание грантов, лекции аспирантам.",
  },
  {
    id: "historian",
    title: "Историк / архивист",
    emoji: "📜",
    short: "Изучает прошлое, работает в архивах, музеях, СМИ.",
    riasec: ["I", "A"],
    values: ["science"],
    abilities: ["verbal", "memory"],
    subjects: ["history", "literature", "social"],
    egeSubjects: ["history", "russian", "literature"],
    universityIds: ["msu", "spbgu", "rggu", "kfu", "omgu"],
    salaryFrom: 40,
    salaryTo: 130,
    outlook: "stable",
    dayInLife: "Работа с источниками, статьи, экспедиции, преподавание.",
  },

  // ─── ГЕОЛОГИЯ / СЕЛЬХОЗ ──────────────────────────────────────────────
  {
    id: "geologist",
    title: "Геолог / нефтяник",
    emoji: "🛢",
    short: "Поиск и разработка месторождений. Высокий доход, командировки.",
    riasec: ["R", "I"],
    values: ["income", "freedom"],
    abilities: ["spatial", "analytical", "mechanical"],
    subjects: ["math", "physics", "geography", "chemistry"],
    egeSubjects: ["math_prof", "physics", "russian"],
    universityIds: ["gornyy", "tindustrial", "sfu", "irnitu", "kazfu-petroleum", "kfu"],
    salaryFrom: 100,
    salaryTo: 500,
    outlook: "stable",
    dayInLife: "Полевые работы вахтой, керн, отчёты, согласование скважин.",
  },
  {
    id: "agronomist",
    title: "Агроном / биотехнолог сельского хозяйства",
    emoji: "🌾",
    short: "Управляет полем или фермой, селекция, новые сорта.",
    riasec: ["R", "I"],
    values: ["stability", "service"],
    abilities: ["analytical", "memory", "mechanical"],
    subjects: ["biology", "chemistry", "geography"],
    egeSubjects: ["biology", "math_prof", "russian"],
    universityIds: ["rgau-msha", "kubgau"],
    salaryFrom: 50,
    salaryTo: 200,
    outlook: "stable",
    dayInLife: "Объезд полей, анализ почв, согласование с агротехникой, отчёты.",
  },

  // ─── СПОРТ / ФИЗКУЛЬТУРА ─────────────────────────────────────────────
  {
    id: "coach",
    title: "Тренер / спортивный методист",
    emoji: "🏆",
    short: "Готовит спортсменов или тренирует группы фитнеса.",
    riasec: ["S", "R"],
    values: ["service", "team"],
    abilities: ["leadership", "social", "mechanical"],
    subjects: ["pe", "biology"],
    egeSubjects: ["biology", "russian"],
    universityIds: ["mpgu"],
    salaryFrom: 40,
    salaryTo: 250,
    outlook: "rising",
    dayInLife: "Тренировки 4–8 часов, общение с подопечными, методическая работа.",
  },

  // ─── ЛОГИСТИКА И ТРАНСПОРТ ───────────────────────────────────────────
  {
    id: "logistician",
    title: "Логист / специалист по транспорту",
    emoji: "🚛",
    short: "Управляет маршрутами, складами, цепочками поставок.",
    riasec: ["C", "E"],
    values: ["stability", "income"],
    abilities: ["analytical", "leadership"],
    subjects: ["math", "social", "geography"],
    egeSubjects: ["math_prof", "social", "russian"],
    universityIds: ["miit", "rgups", "donstu"],
    salaryFrom: 60,
    salaryTo: 200,
    outlook: "rising",
    dayInLife: "Координация перевозок, общение с водителями и клиентами, оптимизация маршрутов.",
  },
];
