import { Question, TestBlock } from "./types";

export const TEST_BLOCKS: TestBlock[] = [
  { code: "interests",  title: "Интересы",                emoji: "🎯", description: "Чем тебе нравится заниматься — без оценок и оплаты. 12 утверждений.", size: 12 },
  { code: "abilities",  title: "Сильные стороны",         emoji: "💪", description: "Что тебе даётся легче, чем сверстникам. 10 утверждений.",        size: 10 },
  { code: "values",     title: "Ценности",                emoji: "🧭", description: "Что для тебя важно в работе и жизни. 10 утверждений.",          size: 10 },
  { code: "subjects",   title: "Школьные предметы",       emoji: "📚", description: "Какие уроки тебе нравятся и удаются. 13 предметов.",           size: 13 },
  { code: "scenarios",  title: "Жизненные ситуации",      emoji: "🎬", description: "Как ты ведёшь себя в типичных ситуациях. 8 ситуаций.",         size: 8 },
  { code: "self",       title: "Самоописание",            emoji: "🪞", description: "Каким ты видишь себя через 10 лет. 8 утверждений.",            size: 8 },
];

// 12 + 10 + 10 + 13 + 8 + 8 = 61 вопрос
export const QUESTIONS: Question[] = [
  // ─── БЛОК 1: ИНТЕРЕСЫ (RIASEC × 2) ────────────────────────────────────
  { id: "i1",  block: "interests", text: "Разбирать на части и собирать обратно: технику, конструкторы, мебель — что-то делать руками",
    scales: [{ kind: "riasec", code: "R" }, { kind: "ability", code: "mechanical" }] },
  { id: "i2",  block: "interests", text: "Решать сложные задачи по математике или ломать голову над логическими загадками",
    scales: [{ kind: "riasec", code: "I" }, { kind: "ability", code: "analytical" }] },
  { id: "i3",  block: "interests", text: "Рисовать, писать рассказы или стихи, сочинять музыку — придумывать что-то своё",
    scales: [{ kind: "riasec", code: "A" }, { kind: "ability", code: "creative" }] },
  { id: "i4",  block: "interests", text: "Объяснять одноклассникам или младшим тему, которую они не поняли на уроке",
    scales: [{ kind: "riasec", code: "S" }, { kind: "ability", code: "social" }] },
  { id: "i5",  block: "interests", text: "Убеждать людей в своей идее так, чтобы они согласились",
    scales: [{ kind: "riasec", code: "E" }, { kind: "ability", code: "leadership" }] },
  { id: "i6",  block: "interests", text: "Раскладывать всё по полочкам — вести списки, таблицы, расписания",
    scales: [{ kind: "riasec", code: "C" }, { kind: "ability", code: "memory" }] },

  { id: "i7",  block: "interests", text: "Изучать, как устроено тело человека, животных и растений",
    scales: [{ kind: "riasec", code: "I" }, { kind: "school", code: "biology" }] },
  { id: "i8",  block: "interests", text: "Следить за новостями: что происходит в стране и мире, как работает экономика",
    scales: [{ kind: "riasec", code: "E" }, { kind: "school", code: "social" }] },
  { id: "i9",  block: "interests", text: "Регулярно заниматься спортом, тренировками и поддерживать своё тело сильным",
    scales: [{ kind: "riasec", code: "R" }, { kind: "school", code: "pe" }] },
  { id: "i10", block: "interests", text: "Писать программы на компьютере или придумывать, как решить задачу шаг за шагом",
    scales: [{ kind: "riasec", code: "I" }, { kind: "school", code: "informatics" }, { kind: "ability", code: "analytical" }] },
  { id: "i11", block: "interests", text: "Ходить в музеи и на концерты, читать книги, которые заставляют думать",
    scales: [{ kind: "riasec", code: "A" }, { kind: "school", code: "literature" }] },
  { id: "i12", block: "interests", text: "Организовывать праздники и мероприятия — собирать команду и всё планировать",
    scales: [{ kind: "riasec", code: "E" }, { kind: "ability", code: "leadership" }, { kind: "value", code: "team" }] },

  // ─── БЛОК 2: СИЛЬНЫЕ СТОРОНЫ ──────────────────────────────────────────
  { id: "a1",  block: "abilities", text: "Я быстро считаю в уме и легко замечаю, какая цифра в ряду пропущена или повторяется",
    scales: [{ kind: "ability", code: "analytical" }, { kind: "school", code: "math" }] },
  { id: "a2",  block: "abilities", text: "Мне легко объяснить любую мысль словами — устно или письменно",
    scales: [{ kind: "ability", code: "verbal" }, { kind: "school", code: "russian" }] },
  { id: "a3",  block: "abilities", text: "Я могу мысленно покрутить объёмную фигуру и представить её с любой стороны",
    scales: [{ kind: "ability", code: "spatial" }, { kind: "school", code: "math" }] },
  { id: "a4",  block: "abilities", text: "Я понимаю, как устроены приборы и техника — могу починить даже без инструкции",
    scales: [{ kind: "ability", code: "mechanical" }, { kind: "riasec", code: "R" }] },
  { id: "a5",  block: "abilities", text: "Я часто придумываю необычные идеи, которые другим не приходят в голову",
    scales: [{ kind: "ability", code: "creative" }, { kind: "riasec", code: "A" }] },
  { id: "a6",  block: "abilities", text: "Я по лицу и голосу понимаю, что человек чувствует, и легко с ним общаюсь",
    scales: [{ kind: "ability", code: "social" }, { kind: "riasec", code: "S" }] },
  { id: "a7",  block: "abilities", text: "У меня хорошая память: легко запоминаю даты, имена, факты и события",
    scales: [{ kind: "ability", code: "memory" }, { kind: "school", code: "history" }] },
  { id: "a8",  block: "abilities", text: "Когда работаем в команде, меня часто выбирают главным или капитаном",
    scales: [{ kind: "ability", code: "leadership" }, { kind: "riasec", code: "E" }] },
  { id: "a9",  block: "abilities", text: "Я быстро учу иностранные языки и понимаю чужую речь на слух",
    scales: [{ kind: "ability", code: "verbal" }, { kind: "school", code: "english" }] },
  { id: "a10", block: "abilities", text: "Я могу долго заниматься одной задачей и не отвлекаться на телефон или болтовню",
    scales: [{ kind: "ability", code: "analytical" }, { kind: "value", code: "stability" }] },

  // ─── БЛОК 3: ЦЕННОСТИ ─────────────────────────────────────────────────
  { id: "v1",  block: "values", text: "Мне важно, чтобы моя будущая работа приносила большие деньги — заметно выше, чем у большинства людей",
    scales: [{ kind: "value", code: "income" }] },
  { id: "v2",  block: "values", text: "Я готов(а) работать на государство ради стабильной зарплаты и уверенности в завтрашнем дне",
    scales: [{ kind: "value", code: "stability" }] },
  { id: "v3",  block: "values", text: "Мне нравится придумывать и создавать то, чего раньше никто не делал",
    scales: [{ kind: "value", code: "creativity" }, { kind: "riasec", code: "A" }] },
  { id: "v4",  block: "values", text: "Я готов(а) помогать людям, даже если за такую работу платят меньше",
    scales: [{ kind: "value", code: "service" }, { kind: "riasec", code: "S" }] },
  { id: "v5",  block: "values", text: "Мне интересно глубоко разбираться, как устроены вещи и явления — не на поверхности, а по-настоящему",
    scales: [{ kind: "value", code: "science" }, { kind: "riasec", code: "I" }] },
  { id: "v6",  block: "values", text: "Я хочу занимать важную должность, принимать решения, чтобы меня уважали и слушали",
    scales: [{ kind: "value", code: "power" }, { kind: "riasec", code: "E" }] },
  { id: "v7",  block: "values", text: "Для меня важно самому выбирать, когда работать и где находиться — без жёсткого начальника и расписания",
    scales: [{ kind: "value", code: "freedom" }] },
  { id: "v8",  block: "values", text: "Я предпочитаю работать в команде — одному(одной) скучно и не очень получается",
    scales: [{ kind: "value", code: "team" }, { kind: "ability", code: "social" }] },
  { id: "v9",  block: "values", text: "Для меня важно служить и защищать свою страну — это серьёзное и достойное дело",
    scales: [{ kind: "value", code: "service" }, { kind: "value", code: "stability" }] },
  { id: "v10", block: "values", text: "Я готов(а) много лет упорно работать над одной целью, если в итоге получится что-то по-настоящему большое",
    scales: [{ kind: "value", code: "science" }, { kind: "ability", code: "analytical" }] },

  // ─── БЛОК 4: ПРЕДМЕТЫ ─────────────────────────────────────────────────
  { id: "s1",  block: "subjects", text: "Математика — мне нравится решать задачи, и у меня получается",                          scales: [{ kind: "school", code: "math" },        { kind: "ability", code: "analytical" }] },
  { id: "s2",  block: "subjects", text: "Физика — мне интересно понимать законы природы: почему всё падает, движется и нагревается", scales: [{ kind: "school", code: "physics" },     { kind: "riasec", code: "I" }] },
  { id: "s3",  block: "subjects", text: "Информатика — мне нравится писать программы и придумывать алгоритмы",                   scales: [{ kind: "school", code: "informatics" }, { kind: "ability", code: "analytical" }] },
  { id: "s4",  block: "subjects", text: "Химия — мне нравится проводить опыты и понимать, из чего состоят вещества",                scales: [{ kind: "school", code: "chemistry" },   { kind: "riasec", code: "I" }] },
  { id: "s5",  block: "subjects", text: "Биология — мне интересно изучать тело человека, растения, животных и природу",            scales: [{ kind: "school", code: "biology" },     { kind: "riasec", code: "I" }] },
  { id: "s6",  block: "subjects", text: "Русский язык — я пишу грамотно и хорошо знаю правила",                                  scales: [{ kind: "school", code: "russian" },     { kind: "ability", code: "verbal" }] },
  { id: "s7",  block: "subjects", text: "Литература — мне нравится разбирать книги и писать сочинения",                            scales: [{ kind: "school", code: "literature" },  { kind: "riasec", code: "A" }] },
  { id: "s8",  block: "subjects", text: "Английский язык — я могу говорить и понимать на слух",                                  scales: [{ kind: "school", code: "english" },     { kind: "ability", code: "verbal" }] },
  { id: "s9",  block: "subjects", text: "История — мне легко запоминаются даты, события и судьбы людей",                          scales: [{ kind: "school", code: "history" },     { kind: "ability", code: "memory" }] },
  { id: "s10", block: "subjects", text: "Обществознание — мне интересно изучать, как устроены законы, экономика и общество",       scales: [{ kind: "school", code: "social" },      { kind: "riasec", code: "E" }] },
  { id: "s11", block: "subjects", text: "География — мне интересно изучать страны, карты, природу и экономику разных регионов",   scales: [{ kind: "school", code: "geography" },   { kind: "ability", code: "spatial" }] },
  { id: "s12", block: "subjects", text: "ИЗО или музыка — мне нравится рисовать, петь, играть на инструменте — я делаю это с удовольствием", scales: [{ kind: "school", code: "art" }, { kind: "riasec", code: "A" }, { kind: "ability", code: "creative" }] },
  { id: "s13", block: "subjects", text: "Физкультура — я люблю двигаться, заниматься спортом, играть в командные игры",            scales: [{ kind: "school", code: "pe" },          { kind: "riasec", code: "R" }] },

  // ─── БЛОК 5: ЖИЗНЕННЫЕ СИТУАЦИИ ───────────────────────────────────────
  { id: "sc1", block: "scenarios", text: "На дне рождения друга мне нравится быть тем, кто весь вечер заряжает компанию энергией",
    scales: [{ kind: "riasec", code: "E" }, { kind: "ability", code: "social" }, { kind: "value", code: "team" }] },
  { id: "sc2", block: "scenarios", text: "Если дома что-то сломалось — например, кран, велосипед или розетка — мне хочется разобрать и починить самому(самой)",
    scales: [{ kind: "riasec", code: "R" }, { kind: "ability", code: "mechanical" }] },
  { id: "sc3", block: "scenarios", text: "Когда я вижу, что кого-то обижают или поступают нечестно — я первым(ой) вступаюсь",
    scales: [{ kind: "value", code: "service" }, { kind: "riasec", code: "S" }] },
  { id: "sc4", block: "scenarios", text: "В свободный вечер мне интереснее почитать статью про науку (например, как устроен мозг), чем посмотреть кино",
    scales: [{ kind: "value", code: "science" }, { kind: "riasec", code: "I" }] },
  { id: "sc5", block: "scenarios", text: "Когда мне дают большое задание — я сначала составляю план и расписываю шаги, а потом уже начинаю делать",
    scales: [{ kind: "riasec", code: "C" }, { kind: "ability", code: "analytical" }] },
  { id: "sc6", block: "scenarios", text: "Однообразные задания мне скучны — я люблю, когда постоянно появляется что-то новое",
    scales: [{ kind: "value", code: "creativity" }, { kind: "value", code: "freedom" }] },
  { id: "sc7", block: "scenarios", text: "Когда я занимаюсь любимым делом (рисую, пишу, играю, мастерю) — я могу забыть про время и про еду",
    scales: [{ kind: "riasec", code: "A" }, { kind: "ability", code: "creative" }] },
  { id: "sc8", block: "scenarios", text: "Когда в классе спорят — я обычно беру слово и могу переубедить даже тех, кто был против",
    scales: [{ kind: "ability", code: "leadership" }, { kind: "value", code: "power" }, { kind: "riasec", code: "E" }] },

  // ─── БЛОК 6: САМООПИСАНИЕ ─────────────────────────────────────────────
  { id: "se1", block: "self", text: "Через 10 лет я хочу стать настоящим экспертом — таким, к которому люди приходят за советом по работе",
    scales: [{ kind: "value", code: "power" }, { kind: "ability", code: "analytical" }] },
  { id: "se2", block: "self", text: "Через 10 лет я хочу создать что-то своё — придумать продукт, открыть свою компанию или запустить бренд",
    scales: [{ kind: "riasec", code: "E" }, { kind: "value", code: "creativity" }, { kind: "value", code: "freedom" }] },
  { id: "se3", block: "self", text: "Через 10 лет я хочу работать там, где каждый день буду спасать жизни или помогать людям с серьёзными проблемами",
    scales: [{ kind: "value", code: "service" }, { kind: "riasec", code: "S" }] },
  { id: "se4", block: "self", text: "Через 10 лет я хочу заниматься наукой — делать открытия, которые узнают во всём мире",
    scales: [{ kind: "value", code: "science" }, { kind: "riasec", code: "I" }] },
  { id: "se5", block: "self", text: "Через 10 лет я хочу служить Родине — в армии, полиции, МЧС или другой государственной структуре",
    scales: [{ kind: "value", code: "service" }, { kind: "value", code: "stability" }, { kind: "riasec", code: "R" }] },
  { id: "se6", block: "self", text: "Через 10 лет я хочу много путешествовать и работать через интернет из любой страны мира",
    scales: [{ kind: "value", code: "freedom" }, { kind: "school", code: "english" }] },
  { id: "se7", block: "self", text: "Через 10 лет я хочу творить — писать книги, снимать фильмы, рисовать картины или выступать на сцене",
    scales: [{ kind: "riasec", code: "A" }, { kind: "value", code: "creativity" }] },
  { id: "se8", block: "self", text: "Через 10 лет я хочу спокойной жизни — своя семья, свой дом и стабильная работа без сюрпризов",
    scales: [{ kind: "value", code: "stability" }, { kind: "value", code: "team" }] },
];