import { Question, TestBlock } from "./types";

export const TEST_BLOCKS: TestBlock[] = [
  { code: "interests",  title: "Интересы",                emoji: "🎯", description: "Чем тебе нравится заниматься — без оценок и оплаты. 12 утверждений.", size: 12 },
  { code: "abilities",  title: "Сильные стороны",         emoji: "💪", description: "Что тебе даётся легче, чем сверстникам. 10 утверждений.",        size: 10 },
  { code: "values",     title: "Ценности",                emoji: "🧭", description: "Что для тебя важно в работе и жизни. 10 утверждений.",          size: 10 },
  { code: "subjects",   title: "Школьные предметы",       emoji: "📚", description: "Какие уроки тебе нравятся и удаются. 13 предметов.",           size: 13 },
  { code: "scenarios",  title: "Жизненные ситуации",      emoji: "🎬", description: "Как ты ведёшь себя в типичных ситуациях. 8 ситуаций.",         size: 8 },
  { code: "self",       title: "Самоописание",            emoji: "🪞", description: "Каким ты видишь себя через 10 лет. 8 утверждений.",            size: 8 },
];

// 12 + 10 + 10 + 13 + 8 + 8 = 61 вопрос
export const QUESTIONS: Question[] = [
  // ─── БЛОК 1: ИНТЕРЕСЫ (RIASEC × 2) ────────────────────────────────────
  { id: "i1",  block: "interests", text: "Разбирать и чинить технику, собирать что-то руками",
    scales: [{ kind: "riasec", code: "R" }, { kind: "ability", code: "mechanical" }] },
  { id: "i2",  block: "interests", text: "Решать сложные задачи и доказывать теоремы",
    scales: [{ kind: "riasec", code: "I" }, { kind: "ability", code: "analytical" }] },
  { id: "i3",  block: "interests", text: "Рисовать, писать рассказы или сочинять музыку",
    scales: [{ kind: "riasec", code: "A" }, { kind: "ability", code: "creative" }] },
  { id: "i4",  block: "interests", text: "Помогать другим разобраться в сложной теме",
    scales: [{ kind: "riasec", code: "S" }, { kind: "ability", code: "social" }] },
  { id: "i5",  block: "interests", text: "Уговаривать, убеждать, продавать идеи",
    scales: [{ kind: "riasec", code: "E" }, { kind: "ability", code: "leadership" }] },
  { id: "i6",  block: "interests", text: "Систематизировать данные, вести списки и таблицы",
    scales: [{ kind: "riasec", code: "C" }, { kind: "ability", code: "memory" }] },

  { id: "i7",  block: "interests", text: "Изучать, как устроены живые организмы",
    scales: [{ kind: "riasec", code: "I" }, { kind: "school", code: "biology" }] },
  { id: "i8",  block: "interests", text: "Читать новости политики и экономики",
    scales: [{ kind: "riasec", code: "E" }, { kind: "school", code: "social" }] },
  { id: "i9",  block: "interests", text: "Заниматься спортом и быть в физической форме",
    scales: [{ kind: "riasec", code: "R" }, { kind: "school", code: "pe" }] },
  { id: "i10", block: "interests", text: "Программировать или придумывать алгоритмы",
    scales: [{ kind: "riasec", code: "I" }, { kind: "school", code: "informatics" }, { kind: "ability", code: "analytical" }] },
  { id: "i11", block: "interests", text: "Посещать музеи, концерты, читать художественную литературу",
    scales: [{ kind: "riasec", code: "A" }, { kind: "school", code: "literature" }] },
  { id: "i12", block: "interests", text: "Организовывать мероприятия и руководить командой",
    scales: [{ kind: "riasec", code: "E" }, { kind: "ability", code: "leadership" }, { kind: "value", code: "team" }] },

  // ─── БЛОК 2: СИЛЬНЫЕ СТОРОНЫ ──────────────────────────────────────────
  { id: "a1",  block: "abilities", text: "Я быстро считаю в уме и легко вижу закономерности в числах",
    scales: [{ kind: "ability", code: "analytical" }, { kind: "school", code: "math" }] },
  { id: "a2",  block: "abilities", text: "Я свободно выражаю мысли словами, у меня широкий словарный запас",
    scales: [{ kind: "ability", code: "verbal" }, { kind: "school", code: "russian" }] },
  { id: "a3",  block: "abilities", text: "Я хорошо представляю в голове 3D-объекты и читаю чертежи",
    scales: [{ kind: "ability", code: "spatial" }, { kind: "school", code: "math" }] },
  { id: "a4",  block: "abilities", text: "Я разбираюсь в технике интуитивно — могу починить без инструкции",
    scales: [{ kind: "ability", code: "mechanical" }, { kind: "riasec", code: "R" }] },
  { id: "a5",  block: "abilities", text: "Я предлагаю нестандартные идеи и решения",
    scales: [{ kind: "ability", code: "creative" }, { kind: "riasec", code: "A" }] },
  { id: "a6",  block: "abilities", text: "Я чувствую настроение людей и легко нахожу подход",
    scales: [{ kind: "ability", code: "social" }, { kind: "riasec", code: "S" }] },
  { id: "a7",  block: "abilities", text: "Я хорошо запоминаю даты, факты, имена",
    scales: [{ kind: "ability", code: "memory" }, { kind: "school", code: "history" }] },
  { id: "a8",  block: "abilities", text: "Меня часто выбирают капитаном/лидером в группе",
    scales: [{ kind: "ability", code: "leadership" }, { kind: "riasec", code: "E" }] },
  { id: "a9",  block: "abilities", text: "Я быстро учусь новым языкам и понимаю чужую речь",
    scales: [{ kind: "ability", code: "verbal" }, { kind: "school", code: "english" }] },
  { id: "a10", block: "abilities", text: "Я могу долго работать над одной задачей, не отвлекаясь",
    scales: [{ kind: "ability", code: "analytical" }, { kind: "value", code: "stability" }] },

  // ─── БЛОК 3: ЦЕННОСТИ ─────────────────────────────────────────────────
  { id: "v1",  block: "values", text: "Мне важно зарабатывать сильно выше среднего",
    scales: [{ kind: "value", code: "income" }] },
  { id: "v2",  block: "values", text: "Я готов(а) работать в государственной организации ради стабильности",
    scales: [{ kind: "value", code: "stability" }] },
  { id: "v3",  block: "values", text: "Мне важно создавать что-то новое, чего раньше не было",
    scales: [{ kind: "value", code: "creativity" }, { kind: "riasec", code: "A" }] },
  { id: "v4",  block: "values", text: "Я хочу помогать людям, даже если за это меньше платят",
    scales: [{ kind: "value", code: "service" }, { kind: "riasec", code: "S" }] },
  { id: "v5",  block: "values", text: "Меня тянет разбираться, как всё устроено на самом деле",
    scales: [{ kind: "value", code: "science" }, { kind: "riasec", code: "I" }] },
  { id: "v6",  block: "values", text: "Я хочу влиять на решения и иметь авторитет",
    scales: [{ kind: "value", code: "power" }, { kind: "riasec", code: "E" }] },
  { id: "v7",  block: "values", text: "Для меня важна свобода — работать когда и откуда хочу",
    scales: [{ kind: "value", code: "freedom" }] },
  { id: "v8",  block: "values", text: "Я расцветаю в команде, в одиночку работать не моё",
    scales: [{ kind: "value", code: "team" }, { kind: "ability", code: "social" }] },
  { id: "v9",  block: "values", text: "Защищать Родину — это серьёзно и для меня лично важно",
    scales: [{ kind: "value", code: "service" }, { kind: "value", code: "stability" }] },
  { id: "v10", block: "values", text: "Я готов(а) посвятить 10 лет одной идее ради большого результата",
    scales: [{ kind: "value", code: "science" }, { kind: "ability", code: "analytical" }] },

  // ─── БЛОК 4: ПРЕДМЕТЫ ─────────────────────────────────────────────────
  { id: "s1",  block: "subjects", text: "Математика — нравится и даётся",                scales: [{ kind: "school", code: "math" },        { kind: "ability", code: "analytical" }] },
  { id: "s2",  block: "subjects", text: "Физика — интересно понять законы природы",      scales: [{ kind: "school", code: "physics" },     { kind: "riasec", code: "I" }] },
  { id: "s3",  block: "subjects", text: "Информатика — программирование, алгоритмы",    scales: [{ kind: "school", code: "informatics" }, { kind: "ability", code: "analytical" }] },
  { id: "s4",  block: "subjects", text: "Химия — нравится экспериментировать и решать", scales: [{ kind: "school", code: "chemistry" },   { kind: "riasec", code: "I" }] },
  { id: "s5",  block: "subjects", text: "Биология — анатомия, генетика, экология",     scales: [{ kind: "school", code: "biology" },     { kind: "riasec", code: "I" }] },
  { id: "s6",  block: "subjects", text: "Русский язык — грамотность мне даётся",       scales: [{ kind: "school", code: "russian" },     { kind: "ability", code: "verbal" }] },
  { id: "s7",  block: "subjects", text: "Литература — анализ текста и сочинения",       scales: [{ kind: "school", code: "literature" },  { kind: "riasec", code: "A" }] },
  { id: "s8",  block: "subjects", text: "Английский язык — говорю и понимаю",         scales: [{ kind: "school", code: "english" },     { kind: "ability", code: "verbal" }] },
  { id: "s9",  block: "subjects", text: "История — даты, события, личности",           scales: [{ kind: "school", code: "history" },     { kind: "ability", code: "memory" }] },
  { id: "s10", block: "subjects", text: "Обществознание — право, экономика, общество",scales: [{ kind: "school", code: "social" },      { kind: "riasec", code: "E" }] },
  { id: "s11", block: "subjects", text: "География — страны, экономика регионов",       scales: [{ kind: "school", code: "geography" },   { kind: "ability", code: "spatial" }] },
  { id: "s12", block: "subjects", text: "ИЗО или музыка — творю с удовольствием",       scales: [{ kind: "school", code: "art" },         { kind: "riasec", code: "A" }, { kind: "ability", code: "creative" }] },
  { id: "s13", block: "subjects", text: "Физкультура — нравится двигаться и спорт",     scales: [{ kind: "school", code: "pe" },          { kind: "riasec", code: "R" }] },

  // ─── БЛОК 5: ЖИЗНЕННЫЕ СИТУАЦИИ ───────────────────────────────────────
  { id: "sc1", block: "scenarios", text: "На дне рождения друга мне комфортнее быть тем, кто оживляет атмосферу",
    scales: [{ kind: "riasec", code: "E" }, { kind: "ability", code: "social" }, { kind: "value", code: "team" }] },
  { id: "sc2", block: "scenarios", text: "Если в школьном проекте что-то ломается — я иду чинить сам(а)",
    scales: [{ kind: "riasec", code: "R" }, { kind: "ability", code: "mechanical" }] },
  { id: "sc3", block: "scenarios", text: "Когда вижу несправедливость — я первым(ой) встаю на защиту",
    scales: [{ kind: "value", code: "service" }, { kind: "riasec", code: "S" }] },
  { id: "sc4", block: "scenarios", text: "В свободное время я предпочту читать про устройство мозга, чем смотреть кино",
    scales: [{ kind: "value", code: "science" }, { kind: "riasec", code: "I" }] },
  { id: "sc5", block: "scenarios", text: "Когда мне дают задачу — я люблю составить план и таблицу",
    scales: [{ kind: "riasec", code: "C" }, { kind: "ability", code: "analytical" }] },
  { id: "sc6", block: "scenarios", text: "Если что-то рутинное — мне скучно, нужны постоянно новые вызовы",
    scales: [{ kind: "value", code: "creativity" }, { kind: "value", code: "freedom" }] },
  { id: "sc7", block: "scenarios", text: "Я могу часами что-то рисовать/писать/делать в любимом деле, забывая о времени",
    scales: [{ kind: "riasec", code: "A" }, { kind: "ability", code: "creative" }] },
  { id: "sc8", block: "scenarios", text: "В споре я обычно беру слово и могу убедить большинство",
    scales: [{ kind: "ability", code: "leadership" }, { kind: "value", code: "power" }, { kind: "riasec", code: "E" }] },

  // ─── БЛОК 6: САМООПИСАНИЕ ─────────────────────────────────────────────
  { id: "se1", block: "self", text: "Через 10 лет я хочу быть востребованным экспертом, к которому идут за советом",
    scales: [{ kind: "value", code: "power" }, { kind: "ability", code: "analytical" }] },
  { id: "se2", block: "self", text: "Через 10 лет я хочу создать что-то своё — продукт, бренд, компанию",
    scales: [{ kind: "riasec", code: "E" }, { kind: "value", code: "creativity" }, { kind: "value", code: "freedom" }] },
  { id: "se3", block: "self", text: "Через 10 лет я хочу спасать жизни и быть нужным людям каждый день",
    scales: [{ kind: "value", code: "service" }, { kind: "riasec", code: "S" }] },
  { id: "se4", block: "self", text: "Через 10 лет я хочу делать научные открытия мирового уровня",
    scales: [{ kind: "value", code: "science" }, { kind: "riasec", code: "I" }] },
  { id: "se5", block: "self", text: "Через 10 лет я хочу служить Родине в погонах или госструктурах",
    scales: [{ kind: "value", code: "service" }, { kind: "value", code: "stability" }, { kind: "riasec", code: "R" }] },
  { id: "se6", block: "self", text: "Через 10 лет я хочу путешествовать и работать из любой точки мира",
    scales: [{ kind: "value", code: "freedom" }, { kind: "school", code: "english" }] },
  { id: "se7", block: "self", text: "Через 10 лет я хочу быть автором — книг, фильмов, картин, концертов",
    scales: [{ kind: "riasec", code: "A" }, { kind: "value", code: "creativity" }] },
  { id: "se8", block: "self", text: "Через 10 лет я хочу иметь семью, дом и спокойный надёжный доход",
    scales: [{ kind: "value", code: "stability" }, { kind: "value", code: "team" }] },
];
