export const SUBJECTS = [
  { id: "all", label: "Все предметы", emoji: "📚" },
  { id: "math", label: "Математика", emoji: "📐" },
  { id: "physics", label: "Физика", emoji: "⚡" },
  { id: "chemistry", label: "Химия", emoji: "🧪" },
  { id: "cs", label: "Информатика", emoji: "💻" },
  { id: "history", label: "История", emoji: "🏛️" },
  { id: "english", label: "Английский", emoji: "🌍" },
  { id: "russian", label: "Русский язык", emoji: "✍️" },
  { id: "biology", label: "Биология", emoji: "🧬" },
  { id: "literature", label: "Литература", emoji: "📖" },
  { id: "geography", label: "География", emoji: "🗺️" },
  { id: "society", label: "Обществознание", emoji: "⚖️" },
];

export const GRADES = [
  { id: "all", label: "Все классы" },
  { id: "1-4", label: "1–4 класс" },
  { id: "5-9", label: "5–9 класс" },
  { id: "10-11", label: "10–11 класс" },
  { id: "ege", label: "ЕГЭ" },
  { id: "oge", label: "ОГЭ" },
];

export const FORMAT = [
  { id: "all", label: "Любой формат" },
  { id: "online", label: "Онлайн" },
  { id: "offline", label: "Офлайн" },
  { id: "video", label: "Видеокурс" },
];

export type SortKey = "popular" | "rating" | "price_asc" | "price_desc" | "new";

export const SORT_OPTIONS: { id: SortKey; label: string }[] = [
  { id: "popular", label: "По популярности" },
  { id: "rating", label: "По рейтингу" },
  { id: "price_asc", label: "Цена: от низкой" },
  { id: "price_desc", label: "Цена: от высокой" },
  { id: "new", label: "Новинки" },
];

export interface Course {
  id: number;
  subject: string;
  title: string;
  tutor: string;
  tutorAvatar: string;
  tutorBadge: string;
  grade: string;
  format: "online" | "offline" | "video";
  price: number;
  priceUnit: string;
  rating: number;
  reviews: number;
  students: number;
  lessons: number;
  duration: string;
  tags: string[];
  color: string;
  emoji: string;
  isNew: boolean;
  isHit: boolean;
  isSale: boolean;
  salePercent?: number;
  trialAvailable: boolean;
  description: string;
}

export const COURSES: Course[] = [
  {
    id: 1,
    subject: "math",
    title: "ЕГЭ Математика: база + профиль",
    tutor: "Алексей Громов",
    tutorAvatar: "👨‍🏫",
    tutorBadge: "Топ репетитор",
    grade: "ege",
    format: "online",
    price: 2500,
    priceUnit: "за урок",
    rating: 4.97,
    reviews: 312,
    students: 1840,
    lessons: 64,
    duration: "90 мин",
    tags: ["ЕГЭ", "Профиль", "База"],
    color: "from-purple-600 to-blue-500",
    emoji: "📐",
    isNew: false,
    isHit: true,
    isSale: false,
    trialAvailable: true,
    description: "Полная подготовка к ЕГЭ с нуля до 90+ баллов. Разбор всех типов задач.",
  },
  {
    id: 2,
    subject: "english",
    title: "Английский с нуля до Upper-Intermediate",
    tutor: "Мария Соколова",
    tutorAvatar: "👩‍🏫",
    tutorBadge: "Носитель языка",
    grade: "5-9",
    format: "online",
    price: 1800,
    priceUnit: "за урок",
    rating: 4.95,
    reviews: 489,
    students: 3200,
    lessons: 96,
    duration: "60 мин",
    tags: ["Разговорный", "Грамматика", "Произношение"],
    color: "from-violet-500 to-purple-600",
    emoji: "🌍",
    isNew: false,
    isHit: true,
    isSale: true,
    salePercent: 20,
    trialAvailable: true,
    description: "Живые диалоги, реальные ситуации. Без скуки — только практика.",
  },
  {
    id: 3,
    subject: "physics",
    title: "Физика: механика и электродинамика",
    tutor: "Дмитрий Волков",
    tutorAvatar: "👨‍🔬",
    tutorBadge: "Кандидат наук",
    grade: "10-11",
    format: "video",
    price: 990,
    priceUnit: "за курс",
    rating: 4.88,
    reviews: 156,
    students: 720,
    lessons: 48,
    duration: "45 мин",
    tags: ["Теория", "Задачи", "ЕГЭ"],
    color: "from-cyan-500 to-blue-600",
    emoji: "⚡",
    isNew: false,
    isHit: false,
    isSale: false,
    trialAvailable: false,
    description: "Понятные объяснения сложных тем. Задачи олимпиадного и ЕГЭ уровня.",
  },
  {
    id: 4,
    subject: "cs",
    title: "Python для школьников: от нуля до проекта",
    tutor: "Кирилл Петров",
    tutorAvatar: "🧑‍💻",
    tutorBadge: "Senior Dev",
    grade: "5-9",
    format: "online",
    price: 2200,
    priceUnit: "за урок",
    rating: 5.0,
    reviews: 201,
    students: 1100,
    lessons: 40,
    duration: "90 мин",
    tags: ["Python", "Проекты", "Олимпиады"],
    color: "from-pink-500 to-rose-600",
    emoji: "💻",
    isNew: true,
    isHit: false,
    isSale: false,
    trialAvailable: true,
    description: "Учим программировать через реальные игры и проекты. Скучно не будет!",
  },
  {
    id: 5,
    subject: "math",
    title: "Математика 5–7 класс: уверенный старт",
    tutor: "Наталья Орлова",
    tutorAvatar: "👩‍🏫",
    tutorBadge: "Стаж 12 лет",
    grade: "5-9",
    format: "offline",
    price: 1500,
    priceUnit: "за урок",
    rating: 4.92,
    reviews: 88,
    students: 430,
    lessons: 36,
    duration: "60 мин",
    tags: ["Алгебра", "Геометрия", "Задачи"],
    color: "from-purple-600 to-blue-500",
    emoji: "📐",
    isNew: false,
    isHit: false,
    isSale: true,
    salePercent: 15,
    trialAvailable: true,
    description: "Закрываем все пробелы в знаниях. Индивидуальный темп.",
  },
  {
    id: 6,
    subject: "russian",
    title: "Русский язык: грамотность за 30 дней",
    tutor: "Светлана Ким",
    tutorAvatar: "👩‍🎓",
    tutorBadge: "Отличник года",
    grade: "5-9",
    format: "video",
    price: 790,
    priceUnit: "за курс",
    rating: 4.9,
    reviews: 267,
    students: 2100,
    lessons: 30,
    duration: "40 мин",
    tags: ["Орфография", "Пунктуация", "ОГЭ"],
    color: "from-rose-500 to-pink-600",
    emoji: "✍️",
    isNew: false,
    isHit: true,
    isSale: false,
    trialAvailable: false,
    description: "30 уроков — и никаких ошибок. Практические упражнения каждый день.",
  },
  {
    id: 7,
    subject: "chemistry",
    title: "Химия: органика для ЕГЭ",
    tutor: "Игорь Лебедев",
    tutorAvatar: "👨‍🔬",
    tutorBadge: "Призёр олимпиад",
    grade: "ege",
    format: "online",
    price: 2800,
    priceUnit: "за урок",
    rating: 4.93,
    reviews: 114,
    students: 580,
    lessons: 52,
    duration: "90 мин",
    tags: ["Органика", "Реакции", "Задачи C"],
    color: "from-green-500 to-teal-600",
    emoji: "🧪",
    isNew: false,
    isHit: false,
    isSale: false,
    trialAvailable: true,
    description: "Всё про органику: механизмы реакций, задачи части C, хитрости.",
  },
  {
    id: 8,
    subject: "history",
    title: "История России: ЕГЭ 80+ баллов",
    tutor: "Андрей Фёдоров",
    tutorAvatar: "👨‍🏫",
    tutorBadge: "Стаж 8 лет",
    grade: "ege",
    format: "online",
    price: 2000,
    priceUnit: "за урок",
    rating: 4.86,
    reviews: 178,
    students: 860,
    lessons: 58,
    duration: "75 мин",
    tags: ["Даты", "Персоналии", "Эссе"],
    color: "from-orange-500 to-amber-500",
    emoji: "🏛️",
    isNew: false,
    isHit: false,
    isSale: true,
    salePercent: 10,
    trialAvailable: true,
    description: "Систематизация всего курса истории. Мнемотехники для дат и событий.",
  },
  {
    id: 9,
    subject: "biology",
    title: "Биология: клетка и генетика для ОГЭ/ЕГЭ",
    tutor: "Ирина Белова",
    tutorAvatar: "👩‍🔬",
    tutorBadge: "Биофак МГУ",
    grade: "oge",
    format: "video",
    price: 1190,
    priceUnit: "за курс",
    rating: 4.91,
    reviews: 93,
    students: 440,
    lessons: 44,
    duration: "50 мин",
    tags: ["Клетка", "Генетика", "Эволюция"],
    color: "from-emerald-500 to-green-600",
    emoji: "🧬",
    isNew: true,
    isHit: false,
    isSale: false,
    trialAvailable: false,
    description: "Самые сложные темы биологии — объяснено простым языком.",
  },
  {
    id: 10,
    subject: "literature",
    title: "Сочинение на 10/10: структура и аргументы",
    tutor: "Елена Чернова",
    tutorAvatar: "👩‍🏫",
    tutorBadge: "Эксперт ЕГЭ",
    grade: "ege",
    format: "online",
    price: 1900,
    priceUnit: "за урок",
    rating: 4.98,
    reviews: 222,
    students: 1340,
    lessons: 24,
    duration: "60 мин",
    tags: ["Сочинение", "Аргументы", "Критерии"],
    color: "from-rose-500 to-pink-600",
    emoji: "📖",
    isNew: false,
    isHit: true,
    isSale: false,
    trialAvailable: true,
    description: "Эксперт ЕГЭ лично проверяет каждое сочинение. Максимальный балл.",
  },
  {
    id: 11,
    subject: "math",
    title: "Математика с нуля: 1–4 класс",
    tutor: "Ольга Сергеева",
    tutorAvatar: "👩‍🏫",
    tutorBadge: "Стаж 15 лет",
    grade: "1-4",
    format: "online",
    price: 1200,
    priceUnit: "за урок",
    rating: 4.96,
    reviews: 345,
    students: 2800,
    lessons: 60,
    duration: "45 мин",
    tags: ["Счёт", "Задачи", "Логика"],
    color: "from-purple-600 to-blue-500",
    emoji: "📐",
    isNew: false,
    isHit: true,
    isSale: false,
    trialAvailable: true,
    description: "Весёлые уроки с картинками и игровыми задачами для малышей.",
  },
  {
    id: 12,
    subject: "society",
    title: "Обществознание: ЕГЭ без паники",
    tutor: "Павел Морозов",
    tutorAvatar: "👨‍💼",
    tutorBadge: "Юрфак МГУ",
    grade: "ege",
    format: "video",
    price: 890,
    priceUnit: "за курс",
    rating: 4.84,
    reviews: 136,
    students: 750,
    lessons: 50,
    duration: "45 мин",
    tags: ["Право", "Экономика", "Эссе"],
    color: "from-indigo-500 to-violet-600",
    emoji: "⚖️",
    isNew: true,
    isHit: false,
    isSale: false,
    trialAvailable: false,
    description: "Системный подбор тем. Разбор всех кодификаторов ЕГЭ 2025.",
  },
];

export const FORMAT_CONFIG = {
  online: { label: "Онлайн", color: "text-cyan-400 bg-cyan-500/15 border-cyan-500/25" },
  offline: { label: "Офлайн", color: "text-orange-400 bg-orange-500/15 border-orange-500/25" },
  video: { label: "Видеокурс", color: "text-green-400 bg-green-500/15 border-green-500/25" },
};
