export const SUBJECTS = [
  { id: "all", label: "Все предметы", emoji: "📚" },
  { id: "math", label: "Математика", emoji: "📐" },
  { id: "physics", label: "Физика", emoji: "⚡" },
  { id: "chemistry", label: "Химия", emoji: "🧪" },
  { id: "cs", label: "Информатика", emoji: "💻" },
  { id: "history", label: "История", emoji: "🏛️" },
  { id: "english", label: "Английский", emoji: "🌍" },
  { id: "russian", label: "Русский язык", emoji: "✍️" },
  { id: "biology", label: "Биология", emoji: "🧬" },
  { id: "literature", label: "Литература", emoji: "📖" },
  { id: "geography", label: "География", emoji: "🗺️" },
  { id: "society", label: "Обществознание", emoji: "⚖️" },
];

export const GRADES = [
  { id: "all", label: "Все классы" },
  { id: "1-4", label: "1–4 класс" },
  { id: "5-9", label: "5–9 класс" },
  { id: "10-11", label: "10–11 класс" },
  { id: "ege", label: "ЕГЭ" },
  { id: "oge", label: "ОГЭ" },
];

export const FORMAT = [
  { id: "all", label: "Любой формат" },
  { id: "online", label: "Онлайн" },
  { id: "offline", label: "Офлайн" },
  { id: "video", label: "Видеокурс" },
];

export type SortKey = "popular" | "rating" | "price_asc" | "price_desc" | "new";

export const SORT_OPTIONS: { id: SortKey; label: string }[] = [
  { id: "popular", label: "По популярности" },
  { id: "rating", label: "По рейтингу" },
  { id: "price_asc", label: "Цена: от низкой" },
  { id: "price_desc", label: "Цена: от высокой" },
  { id: "new", label: "Новинки" },
];

export interface Course {
  id: number;
  subject: string;
  title: string;
  tutor: string;
  tutorAvatar: string;
  tutorBadge: string;
  grade: string;
  format: "online" | "offline" | "video";
  price: number;
  priceUnit: string;
  rating: number;
  reviews: number;
  students: number;
  lessons: number;
  duration: string;
  tags: string[];
  color: string;
  emoji: string;
  isNew: boolean;
  isHit: boolean;
  isSale: boolean;
  salePercent?: number;
  trialAvailable: boolean;
  description: string;
}

export const COURSES: Course[] = [
  // ─── МАТЕМАТИКА ────────────────────────────────────────────────────────────
  {
    id: 1,
    subject: "math",
    title: "ЕГЭ математика профиль: полная подготовка",
    tutor: "ИИ-методист Алексей",
    tutorAvatar: "🤖",
    tutorBadge: "Подготовка к экзамену",
    grade: "ege",
    format: "online",
    price: 0,
    priceUnit: "бесплатно",
    rating: 4.97,
    reviews: 1842,
    students: 12400,
    lessons: 96,
    duration: "45 мин",
    tags: ["Параметры", "Стереометрия", "Производные", "Теория чисел"],
    color: "from-purple-600 to-blue-500",
    emoji: "📐",
    isNew: false,
    isHit: true,
    isSale: false,
    trialAvailable: true,
    description: "Подготовка по официальному кодификатору. Разбираем все 18 заданий: от простых до сложных. Адаптивная программа подстраивается под твой уровень. Пример: задача 13 (тригонометрические уравнения) — учим находить корни на отрезке за 4 шага.",
  },
  {
    id: 2,
    subject: "math",
    title: "Математика 5 класс: дроби и проценты без боли",
    tutor: "ИИ-методист Алексей",
    tutorAvatar: "🤖",
    tutorBadge: "Метод от простого к сложному",
    grade: "5-9",
    format: "online",
    price: 0,
    priceUnit: "бесплатно",
    rating: 4.96,
    reviews: 945,
    students: 8200,
    lessons: 32,
    duration: "20 мин",
    tags: ["Дроби", "Проценты", "Десятичные дроби", "Решение задач"],
    color: "from-purple-600 to-blue-500",
    emoji: "🍕",
    isNew: false,
    isHit: true,
    isSale: false,
    trialAvailable: true,
    description: "Объясняем через пиццу и шоколадки! 3/4 пиццы — это сколько кусков? 25% от 200 рублей — за минуту. Каждый урок начинается с реальной задачи из жизни. Никаких страшных формул — только понимание сути.",
  },
  {
    id: 3,
    subject: "math",
    title: "Геометрия 7–9: теоремы как детектив",
    tutor: "ИИ-методист Алексей",
    tutorAvatar: "🤖",
    tutorBadge: "Авторская методика платформы",
    grade: "5-9",
    format: "video",
    price: 0,
    priceUnit: "бесплатно",
    rating: 4.91,
    reviews: 567,
    students: 4300,
    lessons: 48,
    duration: "25 мин",
    tags: ["Треугольники", "Окружности", "Подобие", "Доказательства"],
    color: "from-purple-600 to-blue-500",
    emoji: "📏",
    isNew: true,
    isHit: false,
    isSale: false,
    trialAvailable: true,
    description: "Каждая теорема — это расследование. Сначала улики (условие), потом версии (предположения), и наконец — разоблачение (доказательство). Пример: теорема Пифагора через площадь квадратов. Раз увидел — навсегда понял.",
  },
  {
    id: 4,
    subject: "math",
    title: "ОГЭ математика 9 класс: уверенная подготовка",
    tutor: "ИИ-методист Алексей",
    tutorAvatar: "🤖",
    tutorBadge: "Систематический разбор",
    grade: "oge",
    format: "online",
    price: 0,
    priceUnit: "бесплатно",
    rating: 4.94,
    reviews: 1203,
    students: 9600,
    lessons: 60,
    duration: "30 мин",
    tags: ["Задание 21", "Геометрия", "Реальная математика", "Алгебра"],
    color: "from-purple-600 to-blue-500",
    emoji: "🎯",
    isNew: false,
    isHit: true,
    isSale: false,
    trialAvailable: true,
    description: "Разбираем каждый тип заданий ОГЭ. Например, задание с планом квартиры: учим читать чертёж и считать площадь паркета за 2 минуты. Цель — уверенно набирать высокие баллы.",
  },
  {
    id: 5,
    subject: "math",
    title: "Олимпиадная математика 6–8 класс",
    tutor: "ИИ-методист Алексей",
    tutorAvatar: "🤖",
    tutorBadge: "Олимпиадные задачи",
    grade: "5-9",
    format: "online",
    price: 0,
    priceUnit: "бесплатно",
    rating: 5.0,
    reviews: 312,
    students: 1800,
    lessons: 40,
    duration: "40 мин",
    tags: ["Принцип Дирихле", "Инварианты", "Графы", "Комбинаторика"],
    color: "from-purple-600 to-blue-500",
    emoji: "🏆",
    isNew: true,
    isHit: false,
    isSale: false,
    trialAvailable: true,
    description: "Учим нестандартному мышлению. Пример: «9 шахматистов сыграли по партии. Доказать, что найдутся двое с одинаковым количеством игр». 5 минут размышления — и видишь принцип Дирихле в действии.",
  },

  // ─── ФИЗИКА ────────────────────────────────────────────────────────────────
  {
    id: 6,
    subject: "physics",
    title: "Физика с нуля: 7-й класс за лето",
    tutor: "ИИ-методист Дмитрий",
    tutorAvatar: "🤖",
    tutorBadge: "Школьная программа + опыты",
    grade: "5-9",
    format: "video",
    price: 0,
    priceUnit: "бесплатно",
    rating: 4.93,
    reviews: 678,
    students: 5400,
    lessons: 36,
    duration: "20 мин",
    tags: ["Давление", "Плотность", "Сила", "Работа"],
    color: "from-cyan-500 to-blue-600",
    emoji: "⚡",
    isNew: false,
    isHit: true,
    isSale: false,
    trialAvailable: true,
    description: "Почему гвозди заострены, а лыжи широкие? Почему лёд легче воды? Каждый урок отвечает на «почему» из жизни. Интерактивные опыты — увидишь, как формула работает на твоих глазах.",
  },
  {
    id: 7,
    subject: "physics",
    title: "ЕГЭ физика: механика наглядно",
    tutor: "ИИ-методист Дмитрий",
    tutorAvatar: "🤖",
    tutorBadge: "Глубокое понимание физики",
    grade: "ege",
    format: "online",
    price: 0,
    priceUnit: "бесплатно",
    rating: 4.95,
    reviews: 892,
    students: 6700,
    lessons: 52,
    duration: "45 мин",
    tags: ["Кинематика", "Динамика", "Импульс", "Энергия"],
    color: "from-cyan-500 to-blue-600",
    emoji: "🚀",
    isNew: false,
    isHit: true,
    isSale: false,
    trialAvailable: true,
    description: "Разбираем задачи на наклонные плоскости, блоки, столкновения — каждую как сцену в фильме. Пример: космонавт прыгает на Луне — как далеко улетит? Применяем 3 формулы, получаем точный ответ.",
  },
  {
    id: 8,
    subject: "physics",
    title: "Квантовая физика для школьников",
    tutor: "ИИ-методист Дмитрий",
    tutorAvatar: "🤖",
    tutorBadge: "Современная физика просто",
    grade: "10-11",
    format: "video",
    price: 0,
    priceUnit: "бесплатно",
    rating: 4.89,
    reviews: 234,
    students: 1900,
    lessons: 24,
    duration: "30 мин",
    tags: ["Двойственность", "Опыт Юнга", "Шрёдингер", "Запутанность"],
    color: "from-cyan-500 to-blue-600",
    emoji: "🌌",
    isNew: true,
    isHit: false,
    isSale: false,
    trialAvailable: true,
    description: "Известный мысленный эксперимент с котом — простыми словами. Что такое квант? Почему фотон одновременно волна и частица? Без сложной математики — только интуиция и яркие визуализации. После курса физика становится понятной.",
  },
  {
    id: 9,
    subject: "physics",
    title: "Электродинамика для ЕГЭ: схемы и поля",
    tutor: "ИИ-методист Дмитрий",
    tutorAvatar: "🤖",
    tutorBadge: "По кодификатору экзамена",
    grade: "ege",
    format: "online",
    price: 0,
    priceUnit: "бесплатно",
    rating: 4.86,
    reviews: 423,
    students: 3100,
    lessons: 40,
    duration: "40 мин",
    tags: ["Закон Ома", "Конденсаторы", "Магнитное поле", "Индукция"],
    color: "from-cyan-500 to-blue-600",
    emoji: "🔌",
    isNew: false,
    isHit: false,
    isSale: false,
    trialAvailable: true,
    description: "Разбор сложных схем за 3 шага: упрощаем → находим ток → считаем напряжение. Пример: смешанное соединение 5 резисторов — решаем за 2 минуты. Магнитное поле объясняем через правило правой руки.",
  },

  // ─── ХИМИЯ ─────────────────────────────────────────────────────────────────
  {
    id: 10,
    subject: "chemistry",
    title: "Химия 8 класс: первые шаги в науке",
    tutor: "ИИ-методист Елена",
    tutorAvatar: "🤖",
    tutorBadge: "Школьная химия + опыты",
    grade: "5-9",
    format: "online",
    price: 0,
    priceUnit: "бесплатно",
    rating: 4.92,
    reviews: 567,
    students: 4200,
    lessons: 34,
    duration: "25 мин",
    tags: ["Атомы", "Молекулы", "Таблица Менделеева", "Уравнения"],
    color: "from-green-500 to-teal-600",
    emoji: "🧪",
    isNew: false,
    isHit: true,
    isSale: false,
    trialAvailable: true,
    description: "Зачем сода + уксус шипят? Почему железо ржавеет? Учим читать формулы — H₂O это просто «два водорода и кислород». Каждый урок — реальный опыт, который можно повторить дома (безопасно!).",
  },
  {
    id: 11,
    subject: "chemistry",
    title: "Органическая химия ЕГЭ: цепочки превращений",
    tutor: "ИИ-методист Елена",
    tutorAvatar: "🤖",
    tutorBadge: "Углублённая программа",
    grade: "ege",
    format: "online",
    price: 0,
    priceUnit: "бесплатно",
    rating: 4.94,
    reviews: 678,
    students: 4500,
    lessons: 58,
    duration: "40 мин",
    tags: ["Алканы", "Спирты", "Бензол", "Задание 32"],
    color: "from-green-500 to-teal-600",
    emoji: "⚗️",
    isNew: false,
    isHit: true,
    isSale: false,
    trialAvailable: true,
    description: "Учим органику не зубрить, а понимать механизмы. Пример: цепочка этан → этен → этанол. Видишь логику переходов — решаешь задания на цепочки за минуты. Сложные реакции через мнемотехники.",
  },
  {
    id: 12,
    subject: "chemistry",
    title: "ОГЭ химия 9 класс: реакции без зубрёжки",
    tutor: "ИИ-методист Елена",
    tutorAvatar: "🤖",
    tutorBadge: "Полный охват тем экзамена",
    grade: "oge",
    format: "video",
    price: 0,
    priceUnit: "бесплатно",
    rating: 4.88,
    reviews: 345,
    students: 2400,
    lessons: 28,
    duration: "30 мин",
    tags: ["Реакции", "Растворы", "Электролиз", "Задачи"],
    color: "from-green-500 to-teal-600",
    emoji: "🔬",
    isNew: true,
    isHit: false,
    isSale: false,
    trialAvailable: true,
    description: "ОГЭ — это набор типовых заданий, и мы разбираем каждое. Расчёт массовой доли через простую пропорцию. Ионные уравнения как пазл: убираем лишнее, оставляем суть. Всё — на понятных примерах.",
  },

  // ─── ИНФОРМАТИКА ──────────────────────────────────────────────────────────
  {
    id: 13,
    subject: "cs",
    title: "Python с нуля: твой первый бот за месяц",
    tutor: "ИИ-методист Кирилл",
    tutorAvatar: "🤖",
    tutorBadge: "Программирование через проекты",
    grade: "5-9",
    format: "online",
    price: 0,
    priceUnit: "бесплатно",
    rating: 5.0,
    reviews: 1456,
    students: 11200,
    lessons: 42,
    duration: "30 мин",
    tags: ["Python", "Telegram-бот", "Проекты", "Без скуки"],
    color: "from-pink-500 to-rose-600",
    emoji: "🐍",
    isNew: false,
    isHit: true,
    isSale: false,
    trialAvailable: true,
    description: "Через 4 недели у тебя свой простой чат-бот, который умеет шутить и считать оценки. Учим программировать через игры: змейка, крестики-нолики, генератор картинок. Скучных лекций не будет — только код и результат.",
  },
  {
    id: 14,
    subject: "cs",
    title: "ЕГЭ информатика: задание 27 (программирование)",
    tutor: "ИИ-методист Кирилл",
    tutorAvatar: "🤖",
    tutorBadge: "Алгоритмы и программирование",
    grade: "ege",
    format: "online",
    price: 0,
    priceUnit: "бесплатно",
    rating: 4.96,
    reviews: 567,
    students: 3800,
    lessons: 48,
    duration: "45 мин",
    tags: ["Задание 27", "Алгоритмы", "Динамика", "Файлы"],
    color: "from-pink-500 to-rose-600",
    emoji: "💻",
    isNew: false,
    isHit: true,
    isSale: false,
    trialAvailable: true,
    description: "Сложное задание ЕГЭ — пишем алгоритм пошагово. Шаблоны решения для типовых задач A, B, C. Пример: поиск максимальной суммы подпоследовательности — кодим на Python за 20 строк. Цель — уверенно набирать баллы за программирование.",
  },
  {
    id: 15,
    subject: "cs",
    title: "Веб-разработка для подростков: сайт за 7 дней",
    tutor: "ИИ-методист Кирилл",
    tutorAvatar: "🤖",
    tutorBadge: "Веб-разработка с нуля",
    grade: "5-9",
    format: "video",
    price: 0,
    priceUnit: "бесплатно",
    rating: 4.93,
    reviews: 423,
    students: 3200,
    lessons: 21,
    duration: "25 мин",
    tags: ["HTML", "CSS", "JavaScript", "Свой сайт"],
    color: "from-pink-500 to-rose-600",
    emoji: "🌐",
    isNew: true,
    isHit: false,
    isSale: false,
    trialAvailable: true,
    description: "За неделю — свой сайт-портфолио в интернете. День 1: HTML (структура). День 3: CSS (красота). День 5: JavaScript (анимации). День 7: публикация. Покажешь друзьям и в школе — все будут в шоке.",
  },
  {
    id: 16,
    subject: "cs",
    title: "Игры на Scratch для младших классов",
    tutor: "ИИ-методист Кирилл",
    tutorAvatar: "🤖",
    tutorBadge: "Визуальное программирование",
    grade: "1-4",
    format: "video",
    price: 0,
    priceUnit: "бесплатно",
    rating: 4.97,
    reviews: 789,
    students: 6800,
    lessons: 24,
    duration: "15 мин",
    tags: ["Scratch", "Игры", "Логика", "Без чтения кода"],
    color: "from-pink-500 to-rose-600",
    emoji: "🎮",
    isNew: false,
    isHit: true,
    isSale: false,
    trialAvailable: true,
    description: "Программируем без кода — собираем игры из ярких блоков визуального редактора. За первый урок — игра «Поймай котика». За месяц — простые аркады, лабиринты, головоломки. Дети учатся думать как программисты, играя.",
  },

  // ─── АНГЛИЙСКИЙ ───────────────────────────────────────────────────────────
  {
    id: 17,
    subject: "english",
    title: "Английский с нуля: говори через 30 дней",
    tutor: "ИИ-методист София",
    tutorAvatar: "🤖",
    tutorBadge: "Разговорный английский",
    grade: "5-9",
    format: "online",
    price: 0,
    priceUnit: "бесплатно",
    rating: 4.95,
    reviews: 2103,
    students: 18400,
    lessons: 30,
    duration: "20 мин",
    tags: ["Speaking", "Базовая грамматика", "500 слов", "Произношение"],
    color: "from-violet-500 to-purple-600",
    emoji: "🌍",
    isNew: false,
    isHit: true,
    isSale: false,
    trialAvailable: true,
    description: "К концу месяца говоришь простыми фразами: о себе, семье, хобби. Короткие уроки и мгновенная практика. Пример: «I like pizza but I don't like olives» — после 3 урока сам строишь похожие предложения.",
  },
  {
    id: 18,
    subject: "english",
    title: "Английский через фильмы и сериалы",
    tutor: "ИИ-методист София",
    tutorAvatar: "🤖",
    tutorBadge: "Живая речь и идиомы",
    grade: "10-11",
    format: "video",
    price: 0,
    priceUnit: "бесплатно",
    rating: 4.98,
    reviews: 1567,
    students: 12800,
    lessons: 45,
    duration: "30 мин",
    tags: ["Сленг", "Идиомы", "Живой английский", "Сериалы"],
    color: "from-violet-500 to-purple-600",
    emoji: "📺",
    isNew: true,
    isHit: true,
    isSale: false,
    trialAvailable: true,
    description: "Разбираем типичные диалоги из современных фильмов и шоу. «It's not rocket science!» — что значит и как использовать. Учишь язык так, как реально говорят сегодня, а не из старых учебников.",
  },
  {
    id: 19,
    subject: "english",
    title: "ЕГЭ английский: уверенная подготовка",
    tutor: "ИИ-методист София",
    tutorAvatar: "🤖",
    tutorBadge: "Все 4 раздела экзамена",
    grade: "ege",
    format: "online",
    price: 0,
    priceUnit: "бесплатно",
    rating: 4.93,
    reviews: 845,
    students: 5200,
    lessons: 50,
    duration: "45 мин",
    tags: ["Чтение", "Аудирование", "Письмо", "Устная часть"],
    color: "from-violet-500 to-purple-600",
    emoji: "🎓",
    isNew: false,
    isHit: true,
    isSale: false,
    trialAvailable: true,
    description: "Все 4 раздела ЕГЭ: чтение (как находить ответ за 30 сек), аудирование (тренируем уши), письмо (структура эссе по критериям), говорение (как не растеряться). Каждый ученик пишет минимум 10 эссе с разбором ИИ-методистом.",
  },
  {
    id: 20,
    subject: "english",
    title: "Грамматика английского: правила без зубрёжки",
    tutor: "ИИ-методист София",
    tutorAvatar: "🤖",
    tutorBadge: "Логика языка",
    grade: "5-9",
    format: "video",
    price: 0,
    priceUnit: "бесплатно",
    rating: 4.91,
    reviews: 678,
    students: 4900,
    lessons: 36,
    duration: "20 мин",
    tags: ["Времена", "Условные", "Артикли", "Модальные"],
    color: "from-violet-500 to-purple-600",
    emoji: "📖",
    isNew: false,
    isHit: false,
    isSale: false,
    trialAvailable: true,
    description: "Времена через визуальные схемы. Present Perfect — это «прошлое с привязкой к настоящему» (I have lost my keys — и до сих пор не нашёл!). Никаких таблиц для зубрёжки — только понимание логики.",
  },

  // ─── РУССКИЙ ЯЗЫК ─────────────────────────────────────────────────────────
  {
    id: 21,
    subject: "russian",
    title: "ЕГЭ русский: высокий балл за сочинение",
    tutor: "ИИ-методист Виктория",
    tutorAvatar: "🤖",
    tutorBadge: "Подготовка к ЕГЭ",
    grade: "ege",
    format: "online",
    price: 0,
    priceUnit: "бесплатно",
    rating: 4.97,
    reviews: 1789,
    students: 13200,
    lessons: 54,
    duration: "40 мин",
    tags: ["Сочинение", "Тестовая часть", "Орфоэпия", "Пунктуация"],
    color: "from-rose-500 to-pink-600",
    emoji: "✍️",
    isNew: false,
    isHit: true,
    isSale: false,
    trialAvailable: true,
    description: "Все типовые задания ЕГЭ с разбором ловушек. Шаблон сочинения по официальным критериям: проблема → комментарий → позиция → согласие → вывод. Учим строить аргументацию на популярные темы.",
  },
  {
    id: 22,
    subject: "russian",
    title: "Орфография за 21 день: писать без ошибок",
    tutor: "ИИ-методист Виктория",
    tutorAvatar: "🤖",
    tutorBadge: "Запоминалки и правила",
    grade: "5-9",
    format: "video",
    price: 0,
    priceUnit: "бесплатно",
    rating: 4.94,
    reviews: 945,
    students: 7600,
    lessons: 21,
    duration: "15 мин",
    tags: ["Корни", "Приставки", "Окончания", "Запоминалки"],
    color: "from-rose-500 to-pink-600",
    emoji: "📝",
    isNew: false,
    isHit: true,
    isSale: false,
    trialAvailable: true,
    description: "Запомни раз и навсегда: «преумный» — значит «очень умный» (приставка ПРЕ = очень). День 1 — корни с чередованием. День 7 — «не» с глаголами. День 21 — пишешь диктант уверенно.",
  },
  {
    id: 23,
    subject: "russian",
    title: "Пунктуация: где запятая, а где нет",
    tutor: "ИИ-методист Виктория",
    tutorAvatar: "🤖",
    tutorBadge: "Авторская методика платформы",
    grade: "5-9",
    format: "online",
    price: 0,
    priceUnit: "бесплатно",
    rating: 4.89,
    reviews: 567,
    students: 4100,
    lessons: 24,
    duration: "20 мин",
    tags: ["Запятые", "Тире", "Двоеточие", "Прямая речь"],
    color: "from-rose-500 to-pink-600",
    emoji: "❗",
    isNew: true,
    isHit: false,
    isSale: false,
    trialAvailable: true,
    description: "«Казнить нельзя помиловать» — запятая решает всё. Учим находить грамматическую основу за 3 секунды. Однородные члены, причастные обороты, вводные слова — каждое правило с яркими примерами.",
  },
  {
    id: 24,
    subject: "russian",
    title: "ОГЭ русский: подготовка 9 класса",
    tutor: "ИИ-методист Виктория",
    tutorAvatar: "🤖",
    tutorBadge: "Все типы заданий ОГЭ",
    grade: "oge",
    format: "online",
    price: 0,
    priceUnit: "бесплатно",
    rating: 4.92,
    reviews: 678,
    students: 5400,
    lessons: 30,
    duration: "30 мин",
    tags: ["Изложение", "Сочинение 9.3", "Тестовая часть"],
    color: "from-rose-500 to-pink-600",
    emoji: "📚",
    isNew: false,
    isHit: false,
    isSale: false,
    trialAvailable: true,
    description: "Изложение по технологии «3 чтения»: первый раз — суть, второй — детали, третий — проверка. Сочинение 9.3 (что такое доброта/дружба) по шаблону: тезис + 2 аргумента + вывод. Цель — стабильно высокие оценки.",
  },

  // ─── ЛИТЕРАТУРА ───────────────────────────────────────────────────────────
  {
    id: 25,
    subject: "literature",
    title: "ЕГЭ литература: классика без боли",
    tutor: "ИИ-методист Виктория",
    tutorAvatar: "🤖",
    tutorBadge: "Анализ литературных произведений",
    grade: "ege",
    format: "online",
    price: 0,
    priceUnit: "бесплатно",
    rating: 4.95,
    reviews: 423,
    students: 2800,
    lessons: 60,
    duration: "45 мин",
    tags: ["Анализ", "Сочинение", "Лирика", "Проза"],
    color: "from-rose-500 to-pink-600",
    emoji: "📖",
    isNew: false,
    isHit: true,
    isSale: false,
    trialAvailable: true,
    description: "Произведения школьной программы с подробным разбором. Крупные романы — за 3 урока главное о персонажах и идеях. Учим писать развёрнутые ответы по официальным критериям. После курса понимаешь смысл классических произведений.",
  },
  {
    id: 26,
    subject: "literature",
    title: "Сочинение на пятёрку: 5-9 класс",
    tutor: "ИИ-методист Виктория",
    tutorAvatar: "🤖",
    tutorBadge: "Структура школьного сочинения",
    grade: "5-9",
    format: "video",
    price: 0,
    priceUnit: "бесплатно",
    rating: 4.88,
    reviews: 345,
    students: 2300,
    lessons: 18,
    duration: "20 мин",
    tags: ["Структура", "Аргументы", "Стиль", "Анализ героев"],
    color: "from-rose-500 to-pink-600",
    emoji: "✒️",
    isNew: true,
    isHit: false,
    isSale: false,
    trialAvailable: true,
    description: "5 типов школьных сочинений — у каждого свой шаблон. Характеристика литературного героя: внешность → поступки → отношение автора → твоя позиция. Готово.",
  },

  // ─── ИСТОРИЯ ─────────────────────────────────────────────────────────────
  {
    id: 27,
    subject: "history",
    title: "ЕГЭ история: ассоциативный метод",
    tutor: "ИИ-методист Андрей",
    tutorAvatar: "🤖",
    tutorBadge: "Систематизация дат и фактов",
    grade: "ege",
    format: "online",
    price: 0,
    priceUnit: "бесплатно",
    rating: 4.93,
    reviews: 678,
    students: 4500,
    lessons: 72,
    duration: "40 мин",
    tags: ["Даты", "Карты", "Историческое сочинение", "Аргументация"],
    color: "from-orange-500 to-amber-500",
    emoji: "🏛️",
    isNew: false,
    isHit: true,
    isSale: false,
    trialAvailable: true,
    description: "Учим даты через мнемотехники: 1242 — Ледовое побоище (12+42=льду конец!). Карты ЕГЭ как пазл: 5 шагов — и определяешь век. Все задания разобраны до автоматизма. Историческое сочинение — по проверенному алгоритму.",
  },
  {
    id: 28,
    subject: "history",
    title: "История России 6-9 класс: интересно как сериал",
    tutor: "ИИ-методист Андрей",
    tutorAvatar: "🤖",
    tutorBadge: "История в формате сериала",
    grade: "5-9",
    format: "video",
    price: 0,
    priceUnit: "бесплатно",
    rating: 4.91,
    reviews: 456,
    students: 3400,
    lessons: 40,
    duration: "20 мин",
    tags: ["Цари", "Войны", "Реформы", "Культура"],
    color: "from-orange-500 to-amber-500",
    emoji: "👑",
    isNew: false,
    isHit: false,
    isSale: false,
    trialAvailable: true,
    description: "История — это люди и интриги. Спорные эпизоды правления Ивана IV — разбираем по источникам. Пётр I — реформатор или тиран? Аргументы за и против. После курса хорошие оценки без зубрёжки, потому что интересно.",
  },
  {
    id: 29,
    subject: "history",
    title: "Всемирная история: от пирамид до интернета",
    tutor: "ИИ-методист Андрей",
    tutorAvatar: "🤖",
    tutorBadge: "Большие исторические идеи",
    grade: "10-11",
    format: "video",
    price: 0,
    priceUnit: "бесплатно",
    rating: 4.94,
    reviews: 345,
    students: 2600,
    lessons: 36,
    duration: "30 мин",
    tags: ["Античность", "Средневековье", "Революции", "XX век"],
    color: "from-orange-500 to-amber-500",
    emoji: "🌍",
    isNew: true,
    isHit: false,
    isSale: false,
    trialAvailable: true,
    description: "Большие идеи: почему рухнул Рим? Как пар изменил мир? Что будет дальше? Учим видеть закономерности, а не запоминать даты. После курса осознаёшь: история — это про настоящее.",
  },

  // ─── БИОЛОГИЯ ────────────────────────────────────────────────────────────
  {
    id: 30,
    subject: "biology",
    title: "ЕГЭ биология: схемы и таблицы",
    tutor: "ИИ-методист Ирина",
    tutorAvatar: "🤖",
    tutorBadge: "Цитология, генетика, экология",
    grade: "ege",
    format: "online",
    price: 0,
    priceUnit: "бесплатно",
    rating: 4.96,
    reviews: 567,
    students: 3800,
    lessons: 64,
    duration: "45 мин",
    tags: ["Цитология", "Генетика", "Эволюция", "Экология"],
    color: "from-emerald-500 to-green-600",
    emoji: "🧬",
    isNew: false,
    isHit: true,
    isSale: false,
    trialAvailable: true,
    description: "Задачи по генетике — наша сильная сторона. Скрещивание Aa × Aa? Решаем за 30 секунд. Цикл Кребса — рисуем схему по памяти. Все типы заданий ЕГЭ с разбором ловушек. Цель — уверенные результаты на экзамене.",
  },
  {
    id: 31,
    subject: "biology",
    title: "Биология 6-9 класс: природа на пальцах",
    tutor: "ИИ-методист Ирина",
    tutorAvatar: "🤖",
    tutorBadge: "Школьная биология + анимации",
    grade: "5-9",
    format: "video",
    price: 0,
    priceUnit: "бесплатно",
    rating: 4.89,
    reviews: 423,
    students: 3200,
    lessons: 38,
    duration: "20 мин",
    tags: ["Растения", "Животные", "Человек", "Клетка"],
    color: "from-emerald-500 to-green-600",
    emoji: "🌿",
    isNew: false,
    isHit: false,
    isSale: false,
    trialAvailable: true,
    description: "Как растения «дышат»? Почему у кошки 9 жизней? Что внутри клетки? Каждый урок — короткое видео с интерактивными опытами. Биология станет любимым предметом — гарантируем.",
  },
  {
    id: 32,
    subject: "biology",
    title: "Анатомия для школьников: твоё тело — космос",
    tutor: "ИИ-методист Ирина",
    tutorAvatar: "🤖",
    tutorBadge: "Анатомия с 3D-моделями",
    grade: "10-11",
    format: "video",
    price: 0,
    priceUnit: "бесплатно",
    rating: 4.92,
    reviews: 234,
    students: 1700,
    lessons: 22,
    duration: "25 мин",
    tags: ["Скелет", "Мышцы", "Мозг", "Сердце"],
    color: "from-emerald-500 to-green-600",
    emoji: "❤️",
    isNew: true,
    isHit: false,
    isSale: false,
    trialAvailable: true,
    description: "Почему сердце не устаёт биться? Как мозг помнит твоё детство? 3D-модели всех систем органов. Учим интересно — как готовиться к медицинскому, или просто понять себя.",
  },

  // ─── ОБЩЕСТВОЗНАНИЕ ─────────────────────────────────────────────────────
  {
    id: 33,
    subject: "society",
    title: "ЕГЭ обществознание: системная подготовка",
    tutor: "ИИ-методист Павел",
    tutorAvatar: "🤖",
    tutorBadge: "Право, экономика, общество",
    grade: "ege",
    format: "online",
    price: 0,
    priceUnit: "бесплатно",
    rating: 4.91,
    reviews: 1234,
    students: 9800,
    lessons: 56,
    duration: "40 мин",
    tags: ["Право", "Экономика", "Социология", "План"],
    color: "from-indigo-500 to-violet-600",
    emoji: "⚖️",
    isNew: false,
    isHit: true,
    isSale: false,
    trialAvailable: true,
    description: "Один из самых сдаваемых экзаменов с массой нюансов. Учим все 5 блоков по официальному кодификатору. Развёрнутые планы — по шаблону. Эссе по обществознанию — учим строить аргументацию. Цель — уверенные баллы.",
  },
  {
    id: 34,
    subject: "society",
    title: "Финансовая грамотность для подростков",
    tutor: "ИИ-методист Павел",
    tutorAvatar: "🤖",
    tutorBadge: "Личные финансы для подростков",
    grade: "5-9",
    format: "video",
    price: 0,
    priceUnit: "бесплатно",
    rating: 4.96,
    reviews: 789,
    students: 6700,
    lessons: 18,
    duration: "15 мин",
    tags: ["Бюджет", "Инвестиции", "Кредиты", "Налоги"],
    color: "from-indigo-500 to-violet-600",
    emoji: "💰",
    isNew: true,
    isHit: true,
    isSale: false,
    trialAvailable: true,
    description: "Что такое инфляция и почему 1000 рублей сегодня — это не та же тысяча через 10 лет? Как откладывать с карманных денег? Что такое акции и как они работают? К концу курса умеешь считать свой бюджет.",
  },

  // ─── ГЕОГРАФИЯ ───────────────────────────────────────────────────────────
  {
    id: 35,
    subject: "geography",
    title: "География России: от Калининграда до Камчатки",
    tutor: "ИИ-методист Ольга",
    tutorAvatar: "🤖",
    tutorBadge: "Интерактивное путешествие",
    grade: "5-9",
    format: "video",
    price: 0,
    priceUnit: "бесплатно",
    rating: 4.93,
    reviews: 345,
    students: 2800,
    lessons: 28,
    duration: "20 мин",
    tags: ["Карта", "Регионы", "Природа", "Города"],
    color: "from-cyan-500 to-blue-600",
    emoji: "🗺️",
    isNew: false,
    isHit: false,
    isSale: false,
    trialAvailable: true,
    description: "Виртуальные путешествия по стране. Почему в Сочи пальмы, а в Якутии вечная мерзлота? Где найти золото и где — самое чистое озеро? Каждый урок — приключение с фактами, которых нет в учебнике.",
  },
  {
    id: 36,
    subject: "geography",
    title: "ОГЭ география: подготовка 9 класса",
    tutor: "ИИ-методист Ольга",
    tutorAvatar: "🤖",
    tutorBadge: "По кодификатору экзамена",
    grade: "oge",
    format: "online",
    price: 0,
    priceUnit: "бесплатно",
    rating: 4.89,
    reviews: 234,
    students: 1900,
    lessons: 24,
    duration: "25 мин",
    tags: ["Карты", "Координаты", "Климат", "Экономика"],
    color: "from-cyan-500 to-blue-600",
    emoji: "🌐",
    isNew: true,
    isHit: false,
    isSale: false,
    trialAvailable: true,
    description: "Работа с картой — за 30 секунд. Координаты как игра: широта — этаж, долгота — квартира. Все типы заданий ОГЭ с практическими приёмами. Цель — уверенная подготовка к экзамену.",
  },
];

export const FORMAT_CONFIG = {
  online: { label: "Онлайн с ИИ", color: "text-cyan-400 bg-cyan-500/15 border-cyan-500/25" },
  offline: { label: "Офлайн", color: "text-orange-400 bg-orange-500/15 border-orange-500/25" },
  video: { label: "Видеокурс", color: "text-green-400 bg-green-500/15 border-green-500/25" },
};